### ISSUE TITLE
Middleware to lower case paths

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#102]
As a User, I want URLs to be case insensitive so that when I share it with my colleagues there is no possibility that they will get 404 due to lower/upper case.

As a Datahub admin, I want all usernames to be lowercased when created so that it is easier to manage.

Create middleware that does toLowerCase for all paths. E.g., atm, this does not work - https://datahub.io/corE

## Acceptance criteria

* [x] I can access https://datahub.io/corE and https://datahub.io/JohnSnowlabs

## Tasks

* [x] create a pull request to make https://github.com/datahq/auth/blob/master/auth/models.py#L74 part case insensitive (https://stackoverflow.com/questions/16573095/case-insensitive-flask-sqlalchemy-query)
* [x] create a pull request to lowercase usernames when creating - https://github.com/datahq/auth/blob/master/auth/models.py#L96
* ~~create a middleware that will lowercase all URLs (usernames and package names) in the frontend~~
* [x] deploy

**Comment by MAliNaqvi** [comment]
Consider lower case as its less prone to error when sharing urls. 

For example github urls are case agnostic:

https://github.com/dataSets/cpi-change
vs
https://github.com/datasets/cpi-change

both work.

**Comment by anuveyatsu** [comment]
FIXED
cc @MAliNaqvi
