### ISSUE TITLE
Zip/sqlite etc output formats

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#105]
As a publisher I want to have a button for downloading a dataset in my preferred format, e.g., zip/sqlite, so visitors of the showcase page can get easily get my dataset and use in their projects.

As a user of DataHub I want to be able to download a dataset in various formats so I can:
* zip - get a dataset in compressed form (so it's a single file, lighter and quicker to download)
* sqlite - use a dataset for my projects (connect to my app, query it)

## Acceptance criteria

* [x] When I arrive at showcase page, I can download the dataset in zip/sqlite format.

## Tasks

* [x] Analysis
* [x] Refactor `extendedToLogical` method to handle `derived/zip` and `derived/sqlite` datahub types
  * [x] treat zip/sqlite formats as non-tabular resources

## Analysis

How do I access zip/sqlite formats?

* There will be an additional resource for it.
  * zip: `resource.datahub.type=derived/zip`
  * sqlite: `resource.datahub.type=derived/sqlite`

Algorithm:

1. when converting "extended" dp to "logical" dp keep zip and sqlite resources as normal
2. add their links in downloads property (should work without changes)
3. render in the template in downloads table

---

# // OLD

In `views/showcase.html`:

```htmlmixed=
<!-- short readme -->
<div class="readme-snippet readable-width">{{dataset.readmeSnippet}} <a href="#readme" onclick="scrollDown(this)">read more</a></div>

<!-- download button -->
<a href="#data" class="btn btn-lg btn-primary" onclick="scrollDown(this)">Download</a>

<!-- download dataset in zip/sqlite -->
{% for output in dataset.outputs %}
<div>
  <a href="{{output.path}}" class="btn btn-lg">Download {{output.format}}</a>
</div>
{% endif %}
```

so it is rendered as separate buttons next to current `Download` button, but it should standout or just differ by color.

**Comment by zelima** [comment]
@anuveyatsu think we can close this as fixed and reopen if needed

**Comment by anuveyatsu** [comment]
FIXED - closing for now as Frontend part is done here. We'll reopen if something comes up after backend implementation.
