### ISSUE TITLE
Pipelines page improvements

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#109]
Pipelines page needs some definite tidying up and improvement e.g. add a data, colouring etc. Plus messages are pretty unhelpful :-) e.g. https://datahub.io/core/country-list/pipelines 

## Acceptance criteria

* [ ] state is stand out from rest of the content with appropriate colouring
  * [ ] red if failed/invalid
  * [ ] green if succeeded
* [ ] title probably does not need publisher name - just a dataset name
* [ ] logs are clear

## Tasks

* [ ] redesign title/state part - should be simple & elegant (state should stand out)
* [ ] rework showing logs
  * [ ] analysis on what to show
  * [ ] container box for logs
    * see heroku example
    * see docker example
  * [ ] implementation
* [ ] have some info message underneath of the page like in blog posts saying how users can reach datahub team or create issues

**Comment by anuveyatsu** [comment]
INVALID, we don't have `/pipelines` page anymore.
