### ISSUE TITLE
Blog post route and page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#110]
Implement blog post page and route.

## Acceptance criteria

* [x] `/blog/space-usage` opens blog post about space usage

## Tasks

* [x] parse frontmatter - use e.g. https://www.npmjs.com/package/front-matter
  * [x] template for page (like docs?)
    * [x] date, authors, title
    * [x] content
  * [x] Connect content and template
* [x] test

**Comment by anuveyatsu** [comment]
FIXED:

<img width="881" alt="screen shot 2017-10-04 at 14 23 25" src="https://user-images.githubusercontent.com/17809581/31166171-9c26d69c-a90f-11e7-92a2-3de6937cc081.png">
