### ISSUE TITLE
Preview placeholder for non-tabular resources

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#111]
At the moment, if we go to showcase page of a dataset with a non-tabular resource, there would be no preview. It would have a title of the resource but no content underneath, which does not look great.

- `states` resource - http://datahub.io/examples/vega-views-tutorial-topojson
- `excel` resource - https://datahub.io/anuveyatsu/excel-lucky-monkey-72

This is happening because we cannot display non-tabular resources as tables so our `frontend-showcase-js` library skipping such files when creating preview containers.

We could implement something like preview placeholders, e.g., see Github example https://github.com/datapackage-examples/excel/blob/master/excel.xlsx :

<img width="989" alt="screen shot 2017-10-06 at 10 53 57" src="https://user-images.githubusercontent.com/17809581/31263536-b02e5f40-aa84-11e7-8b99-7f30d3364cf0.png">

Notice, `topojson` is implemented in github - https://github.com/datapackage-examples/vega-airports/blob/master/data/us-10m.json

## Acceptance criteria

* [ ] 2 examples above do not have empty space in previews - they have nice placeholders

## Tasks

* [ ] analysis
* [ ] mockup of the placeholder
* [ ] refactor the template

// EXTRA
* [ ] have file size/rowcount next to each preview table's title

## Analysis

* Where to implement, frontend OR frontend-showcase-js?
  * We cannot implement it in `dpr-js` because it looks up for views to render preview components (and we're not going to generate preview views for such resources). So we need to implement this in the frontend.

As a placeholder, we can have a box with a light grey background. In the middle of the box, we can inform users that this resource does not have a preview but they can view raw content (link).

### Implementation

We just need to have placeholder element in `resource-preview` div elements. It would be replaced by `dpr-js` if there is a preview component. Rendering process would be:

1. Initial template rendering - have placeholders for all previews
2. Once `dpr-js` is loaded it replaces previews with generated components (handsontable, leafletmap, more when we implement)
3. If there is no preview component, a placeholder would remain.

**Comment by zelima** [comment]
Think this is FIXED. We are saying:
>This is a preview version. There might be more data in the original version.
