### ISSUE TITLE
Refactor rendering licenses property

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#112]
Currently:

```html
{% if dataset.licenses %}
<i class="fa fa-gavel"></i> <a href="{{dataset.licenses[0].url}}" title="Available under the following License">{{dataset.licenses[0].name or dataset.licenses[0].id}}</a>
{% elif dataset.license %}
<i class="fa fa-gavel"></i> {{ dataset.license }}
{% endif %}
```

instead, we have to expect `licenses` to be an array of objects only as per specs - https://specs.frictionlessdata.io/data-package/#licenses

Also, use `name`, `title` and `path` properties appropriately so it is useful:

* use `name` for display
* use `title` for hover info
* use `path` to linkify

## Acceptance criteria

* [x] properties are used as above ^

## Tasks

* [x] refactor `showcase.html` template as per description of this issue

EXTRA
* [x] refactor `listify` snippet, which is used for rendering `sources` property, to don't be a link if `path` property is not provided. Otherwise, it is linked to the showcase page itself, see http://datahub.io/core/finance-vix

**Comment by anuveyatsu** [comment]
FIXED
