### ISSUE TITLE
Misc improvements

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#113]
In this issue, we will list misc items related to the frontend. Append new items in the tasks section below. Estimate of the issue will be changed as items added.

## Tasks

* [x] docs/blog page improvements (info boxes, images, margins, paddings) [30m]
* [x] dashboard page - have username as main info and email as secondary underneath [90m]
* [x] up number of datasets shown on profile page by default to 100 [15m]
* [x] have a note under the preview tables saying that it is preview (10k rows and have a link to csv file) [30m]
* [x] move images for docs and blog posts into subfolder “/static/images/docs/` [15m]
* [x] code highlighting does not work in docs/blog pages [1h]

**Comment by anuveyatsu** [comment]
FIXED
