### ISSUE TITLE
Update usage instructions on showcase page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#115]
Usage instructions from various softwares are now seems not working due to massive changes in the backend. We want to update them so users can still follow those instructions.

## Acceptance criteria

* [ ] All instructions on showcase page are upto date and working

## Tasks

* [x] Update R instructions
* [x] Updates Pandas instructions
* [x] Update Python instructions
* [ ] Update SQL instructions
  * [ ] copy the code from current instruction (from datahu.io showcase page) and update so that it works on your local machine 
* [x] Update JS instructions according to `data.js` library

## Analysis

R/Pandas/Python/SQL:

Check if we're using correct path when reading a datapackage, e.g., for R:

```
datapackage <- datapkg_read("https://pkgstore.datahub.io/f512ef8d39ada702fde60efe1ca59c17/farm-survey/latest")
```

and update the dataset path with actual working one.

Javascript:

Options:

1. Update instrucitons with usage of `data.js` library instead of `datapackage-js`
2. We're using `datapackage-js` lib of version 0.8.1. We need to update instructions with usage of v1.

**Comment by Mikanebu** [comment]
R is outdated for https://github.com/ropenscilabs/datapkg. Second library does not have a usage section in README https://github.com/okgreece/datapackage-r. Python example is updated with new version datapackage@1.1, currently we do not have a PHP example, do I need to create one? Also, I could not find examples, or usage for PANDAS and SQL
```
/Users/Zhiyenbayev_mirza/anaconda3/lib/python3.6/site-packages/datapackage/pushpull.py:39: UserWarning: Functions "push/pull_datapackage" are deprecated. Please use "Package" class UserWarning) /Users/Zhiyenbayev_mirza/anaconda3/lib/python3.6/site-packages/datapackage/resource.py:406: UserWarning: Property "resource.table" is deprecated. 
Please use "resource.iter/read" directly. UserWarning). 
````
I could not find examples, they are outdated here https://github.com/frictionlessdata/tableschema-pandas-py

**Comment by anuveyatsu** [comment]
UPDATE:

* SQL instructions are broken
* we now also have Ruby and PHP instructions:
  * Ruby is tested but PHP is not
  * we need to add them into the site once both are tested

**Comment by rufuspollock** [comment]
@Mikanebu @anuveyatsu can you guys get this complete - or leave out the SQL instructions for now (and open a special issue just for that).

**Comment by anuveyatsu** [comment]
FIXED

* updated R, Python, Pandas, JS instructions
* we've removed SQL instructions as it is not working atm - https://github.com/datahq/frontend/issues/124
* added new instructions re Ruby
* didn't add PHP instructions as upstream library is out of date
