### ISSUE TITLE
Improvements in "author" of blog posts/docs

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#116]
- Implement having multiple authors on blog posts;
- Using username instead of full name (username in frontmatter but full name on blog post (with link to their user account));
- Making username a link to publisher page

## Acceptance criteria

* [x] Points above are complete

## Tasks

* [x] "author" property in frontmatter should be array so we can have multiple authors
* [x] refactor "authors" dictionary so we can reference author by username (but still display full name)
* [x] make author names linkable - should link to publisher page

**Comment by anuveyatsu** [comment]
FIXED
