### ISSUE TITLE
Show events on the dashboard page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#118]
As a Publisher I want to see what has happened recently with my data (and in future what my team has done) so that I know things are working, what’s changed etc.

In the dashboard page, we want to show user related events. E.g., push completion of user's datasets. By default, we can show all events in descending order (newest on the top) with an option to filter only datasets related ones. This is useful because usually events such as "sign in" happen a lot but they're not useful.

In the dashboard page, have a switcher button with two options: "All events" and "Dataset events". Show "All events" by default.

## Acceptance criteria

* [x] when I arrive at dashboard page, I can see all events related to my datasets (that are available from API)

## Tasks

* [x] new method in Datahub api class to call events store API
* [x] refactor dashboard route to hit events store API and pass results to the template
* [x] refactor dashboard.html to show events
  * [x] mockup
  * [x] implement html + sass

## Analysis

Hit the event store API with following parameters:

* owner - user's id
* include auth token in the headers so we get events for unlisted/private datasets
* `size=10` - as the most recent 10 events look enough

```javascript=
// DataHubApi class
async getEvents(userid, token) {
  // hit the api and return the json response
}
```

In the `dashboard` route:

```javascript=
const events = await api.getEvents(req.cookies.id, req.cookies.jwt)
const datasetEvents = events.filter(event => event.event_entity === 'flow')
// pass to template
```

**Comment by anuveyatsu** [comment]
FIXED, expecting two types (`event_entity`) of events: flow and account. We indicate flow events with "file-code" icon (this is what I found the most appropriate) and have information such as dataset name (link to showcase page) and event action (e.g., finished). For account events, we have `user` icon + statement of what was done. For both events we have timestamp in "timeago" format. See screenshots below (there are no account events atm as it is not yet implemented in the backend):

<img width="1020" alt="screen shot 2017-10-24 at 00 21 06" src="https://user-images.githubusercontent.com/17809581/31905877-55a9679c-b851-11e7-9b02-b4ba11684afb.png">

and full page:

<img width="1280" alt="screen shot 2017-10-24 at 00 20 57" src="https://user-images.githubusercontent.com/17809581/31905895-62dec6a0-b851-11e7-8b94-ac31ba2b7db1.png">
