### ISSUE TITLE
Show events on publisher page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#120]
As a Viewer I want to see what a Publisher has been up to so that I know whether they are active, what's new and what's hot (so that ...)

## Acceptance criteria

* [x] when I arrive at https://datahub.io/core I can see recent events for the user
  * [x] last 10 events

## Tasks

* [x] call `api.getEvents` from `/{owner}` route with appropriate query and pass results to the template
* [x] refactor `owner.html`
  * [x] mockup
  * [x] implement html+sass

## Analysis

Query: `?owner="{username}"&size=10"`

See new mockups below in the comments.

// OLD

Mockup:

Stats (events), see under the gravatar. This is very basic but useful numbers. The termometer indicates how active is the user last month (e.g., we can how 4 levels - empty, half empty, full, full+orange). The star indicates number of datasets the user has (or contributed to, not sure if user can contribute other than his/her own datasets though) and also with the same 4 levels. We need to decide about breakpoints. See mockup:

https://i.imgur.com/DfQx2SJ.png

**Comment by rufuspollock** [comment]
@anuveyatsu i actually want to see an activity stream here as well as summary stats. In fact I'd say the activity stream is more important. Longer term we'd want activity grid a la e.g. github.

So ... right now I'd focus on the activity stream. Stats are also nice if not much work (but i'm concerned they are non-trivial in the backend ...?)

**Comment by anuveyatsu** [comment]
@rufuspollock after our discussion I have implemented activity stream in the dashboard page #118 and now adapted it for publisher page. Please, see screenshots below (there are 3 of them):

<img width="316" alt="screen shot 2017-10-24 at 12 16 04" src="https://user-images.githubusercontent.com/17809581/31927415-be8f7120-b8b5-11e7-9c5d-b576fbcb2e2e.png">

<img width="1280" alt="screen shot 2017-10-24 at 12 16 00" src="https://user-images.githubusercontent.com/17809581/31927416-beb2bde2-b8b5-11e7-9413-014e346c2219.png">

<img width="1280" alt="screen shot 2017-10-24 at 12 15 51" src="https://user-images.githubusercontent.com/17809581/31927417-bed59d44-b8b5-11e7-8b20-92de6d8dd02f.png">

**Comment by anuveyatsu** [comment]
FIXED, see screenshots in the previous comment.
