### ISSUE TITLE
[docs] Add new docs: "automated preview tables"

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#126]
*As a DataHub user I want to know what's are preview tables and how they work so I know what to expect when I push my dataset to DataHub.*

## Tasks

* [x] Add new docs: "automated preview tables"
  * [x] intro paragraph: we auto generate preview versions and display them in the table so users can get sense of what's in. Preview versions have first 5k rows
  * [x] preview tables are generated only for tabular data (and have a link to read more about tabular data)

**Comment by rufuspollock** [comment]
@anuveyatsu can we get a user story - or is that in the epic?

**Comment by anuveyatsu** [comment]
@rufuspollock updated description with a user story ^^

**Comment by rufuspollock** [comment]
@anuveyatsu perfect. Let's get this done.

**Comment by anuveyatsu** [comment]
FIXED - http://datahub.io/docs/features/preview-tables-for-your-data
