### ISSUE TITLE
[docs] Add new docs: "automated zip, csv and json generation"

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#127]
*As an admin I want to have docs about automated zip/csv/json versions so users know about the feature/added value*.

*As a user of DataHub I want to know about important features provided by DataHub so I know what value I am getting.*

## Tasks

* [x] Add new docs: "automated zip, csv and json generation"
  * [x] intro paragraph: we auto generate compressed zip version of dataset so people can quickly download entire package
    * [x] we also generate CSV (cleared/standardized?) and JSON versions of data (if it is tabular)
  * [x] 3 small paragraphs for each generated version with screenshot where are links placed on the page

**Comment by anuveyatsu** [comment]
FIXED - http://datahub.io/docs/features/auto-generated-csv-json-and-zip
