### ISSUE TITLE
Write API Tests

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#128]
We want to test all API endpoints, so all our serves works fine and returns a valid response. 

## Acceptance criteria

* [ ] All API tests are tested on `travis` automatically

## Tasks

* [ ] list out all the services with API endpoint
* [ ] prepare request body

**Comment by rufuspollock** [comment]
@Mikanebu are these functional ("black box") tests or tests here in this library. Also the library has no API so i was wondering what APIs you meant ...?

**Comment by Mikanebu** [comment]
@rufuspollock not for this library, all API from metastore, rawstore  and so on. Probably it should go `pm` repo

**Comment by rufuspollock** [comment]
@Mikanebu yes this issue should not be here. Can you move it please (use the move issue button on the side).
