### ISSUE TITLE
Change front/dashboard pages with download desktop app info

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#130]
We want users to easily find where to download our Electron app (also cli binaries) from front and dashboard pages.

## Acceptance criteria

* [x] Clear indication of where I can download desktop app on front and dashboard pages

## Tasks

* [x] remove banner saying this is alpha (leave just survey message ...) [5m]
* [x] download link in navbar [10m]
* [x] have a "Get started" button next to explore datasets button [10m]
* [x] on the dashboard page, have a prominent button to download apps [20m] - "To start publishing data [download the desktop app and command line tool now]{link}!"

**Comment by anuveyatsu** [comment]
FIXED - now available for testing and will be live in production after next redeploy:

Front page:
![welcome home datahub frictionless data](https://user-images.githubusercontent.com/17809581/32993337-d1fe58fe-cd80-11e7-9845-9affe56e8f3f.png)

Dashboard page:
![dashboard datahub frictionless data](https://user-images.githubusercontent.com/17809581/32993339-da95d7f8-cd80-11e7-8388-c2a26c722851.png)
