### ISSUE TITLE
Download page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#131]
As now we have desktop app to keep CLI tool up to date, we want our main call to action to be about downloading that app.

## Acceptance criteria

* [x] nice download page at `/download`

## Tasks

* [x] download page (desktop app on top then comes cli binaries) [2h]
  * [x] design layout
  * [x] implement
* [x] all download links should be tracked with GA [30m]

## Analysis

Initial mockup as below. We will add more description like what you can do, eg, push/edit/manage datasets later. The screenshot should be replaced with nice one inside some iMac device probably:

Our app is the recommended way to put data on the DataHub and use its services.
It also installs and maintains the command line program up to date automatically.

![download page](https://user-images.githubusercontent.com/17809581/32846965-dba9b168-ca52-11e7-87da-c36b03ba8394.png)

**Comment by anuveyatsu** [comment]
FIXED - atm available for testing and will be live in production after redeploy:

![download datahub frictionless data](https://user-images.githubusercontent.com/17809581/32993352-fcd261c4-cd80-11e7-8f2b-420502e80315.png)
