### ISSUE TITLE
Logged in status check should happen in browser

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#134]
Right now, we are setting login status in `res.locals` object depending on if there is `jwt` value in cookies. This is ok, but if we need to cache some static pages, e.g., `/download` page this can cause bugs - it would return same cached template page to different users:

1. User 1 requests the page and he's logged in so navbar would show him his gravatar
2. User 2 requests the page within 10m and he gets the same page as the User 1, however, he's not logged in

https://github.com/datahq/frontend/blob/master/index.js#L33-L37

The quickest way to resolve this right now is to check cookies in the browser with the script. With similar approach we've implemented showing gravatar in the navbar.

NOTE: we need to cache `/download` page because we're making API requests to Github and they have restriction of 60 requests per hour (more for authenticated users but still there is a limit so we want to make sure that we dont exceed that limit).

## Acceptance criteria

* [x] Cached pages behave correctly

## Tasks

* [x] remove login status from `locals` object
* [x] create a small script for checking login status and setting appropriate links in the navbar

**Comment by anuveyatsu** [comment]
FIXED

**Comment by rufuspollock** [comment]
@anuveyatsu i don't like moving this to javascript so much i have to say as it adds complexity (there will be lots of places where knowing you are logged in will matter and we can't use JS everywhere).

Overall when i saw the caching of the download page i worried a bit as it seems to add a lot of complexity for something quite simple. I'm wondering if there is a way to cache the API call results rather than the download page itself -- or to stop caching entirely and simply update the download page manually for now (or have it point to the a release page at least for the cli).

**Comment by anuveyatsu** [comment]
@rufuspollock got it - now re-implemented this using GitHub's conditional requests (https://developer.github.com/v3/#conditional-requests): https://github.com/datahq/frontend/commit/623381ac9490a797cda2e243afb7c02e1f962d8b
