### ISSUE TITLE
URL scheme changes: short url logic changes

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#140]
* (short url:) `<owner>/<dataset-name>`
  * Shows the showcase for the latest sucessful revision
  * If no such revision exists (i.e. no revision is successfull or no revisions exist), then show 404

## Acceptance criteria

* [x] when I visit showcase page I see the latest succeeded revision
* [x] if no latest successful revision then I get 404

## Tasks

* [x] add tests
* [x] refactor `pipelineStats` method (see analysis)
* [x] refactor `getPackageFile` and `getPackage` methods (see analysis)
* [x] refactor route for showcase page (see analysis)

## Analysis

- How to get status of specific revision?
  - Need to add an API for that in specstore
- How to get status of latest successful revision?
  - Need to add an API for that in specstore

To get status for specific revision, we will be passing revision id as query params, eg, `/source/owner/dataset-name/info?revision=revision_id`. So in the lib, refactor `pipelineStatus` method of DataHubApi class so it handles params:

```javascript=
class DataHubApi {
  ...
  async pipelineStatus(ownerid, name, appendix, params) {
    let url = `${this.FLOWMANAGER_API}/source/${ownerid}/${name}/${appendix}`
    if (params) {
      let query = ''
      for (var key in params) {
        query += `${key}=${params[key]}&`
      }
      url += `?${query}`
    }
    const response = await fetch(url)
    if (response.status !== 200) {
      throw response
    }
    const out = await response.json()
    return out
  }
  ...
}
```

To be able to get datapackage.json for specific revision, we also need to refactor `getPackageFile` of DataHubApi class:

```javascript=
async getPackageFile(ownerid, name, path = 'datapackage.json', token=null, revisionId = 'latest') {
  const url = urllib.resolve(this.bitstoreUrl,
      [ownerid, name, revisionId, path].join('/')
      )
  ...
}
```

Then refactor route for showcase page so it shows the latest successful revision:

```javascript=
app.get('/:owner/:name', async (req, res) => {
  ...
  const userAndPkgId = await api.resolve(path.join(req.params.owner, req.params.name))
  const latestSuccessfulRevision = await api.pipelineStatus(userAndPkgId.userid, userAndPkgId.packageid, 'latest-successful')
  if (!latestSuccessfulRevision) {
    res.status(404).send('Sorry, this page was not found.')
    return
  }
                                              
  ...
  status = await api.pipelineStatus(
    userAndPkgId.userid,
    userAndPkgId.packageid,
    'info',
    {revision: latestSuccessfulRevision}
  )
  ...
  // then use that ID to get datapackage and status
  normalizedDp = await api.getPackage(
    userAndPkgId.userid,
    userAndPkgId.packageid,
    revisionId,
    token
  )
  ...
})
```

**Comment by anuveyatsu** [comment]
FIXED, e.g. visiting this http://testing.datahub.io/core/finance-vix is identical to http://testing.datahub.io/core/finance-vix/v/37 which is the latest successful revision right now (but it won't be later as new revisions to come)
