### ISSUE TITLE
URL scheme changes: full url

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#141]
(full url:) `<owner>/<dataset-name>/v/<revision-id>`
Shows the showcase for a specific revision
  
- Showcase page [for revisions]
  - If revision succeeded (^2)
    - Show showcase as now from processed datapackage
    - Resources with failed validations (^3) should be marked as such with a warning sign
      - If latest successful revision: redirect to short url (need to see how) ^9
  - If revision failed (^2)
    - Show showcase from the original datapackage
      - We show only the original resources, not the derived ones (as they don't exist in the original datapackage)
    - Resources with failed validations (^5) should be marked as such with a warning sign
    - Clearly show an error indication and which step failed (^3) (as well as some way to see the error message)
  - If revision in progress (^2):
    - Show showcase from the original datapackage
    - Clearly show a progress indication and which step is currently running (^8) (as well as some way to see the error message)
    - Keep on polling until revision either succeeds or fails
    - If failed
      - Reload the page to get to failed view
    - If successful
      - Redirect to 'short url' (should show same revision as it's now the latest successful revision)

## Acceptance criteria

* [x] when I visit showcase with full url, I see the page for that specific revision according to algorithm above

## Tasks

* [x] create a new route `'/:owner/:name/v/:revisionId'` as per analysis below
  * [x] create a new route using short showcase url route
  * [x] prepare `renderPage` function for new logic
  * [x] handle when `SUCCESS`
  * [x] handle when `FAIL`
  * [x] handle when `INPROGRESS`

## Analysis

How to get status of specific revision?
Using the following api: `/source/owner/dataset-name/info?revision=revision_id`

What exactly will be fixed in this issue:

* SUCCESS:
  * FIXED: show the page normally
  * NOT FIXED: showing validation errors - this is a separate issue
  * NOT FIXED: redirecting to short URL - this will be done later separately
* FAIL:
  * FIXED: show the page using original dp.json
  * NOT FIXED: validation errors - separate issue
  * NOT FIXED: which steps are failed - for now just say FAILED
* INPROGRESS:
  * FIXED: show the page using original dp.json
  * FIXED: redirecting if failed or succeeded
  * FIXED: keep on polling
  * NOT FIXED: showing which step is running - another issue (but for now say it is running)
  * NOT FIXED: showing occured errors - another issue

```javascript=
app.get('/:owner/:name/v/:revisionId', async (req, res) => {
  let normalizedDp = null
  let token = req.cookies.jwt
  const userAndPkgId = await api.resolve(path.join(req.params.owner, req.params.name))

  ...
  status = await api.pipelineStatus(
    userAndPkgId.userid,
    userAndPkgId.packageid,
    'info',
    {revision: req.params.revisionId}
  )
                                                            
  if (status.state === 'SUCCESS') {
    // render the page normally getting package etc.
  } else if (status.state === 'FAIL') {
    // Use original dp.json:
    normalizedDp = status.spec_contents.inputs[0].parameters.descriptor
    renderPage(...)
  } else if (status.state === 'QUEUED' || status.state === 'INPROGRESS') {
    normalizedDp = status.spec_contents.inputs[0].parameters.descriptor
    renderPage(...)
  }
               
  async function renderPage(status) {
    ...
    res.render('showcase.html', {
      title: ...,
      ...,
      statusApi: `${config.get('API_URL')}/source/${userAndPkgId.userid}/${userAndPkgId.packageid}/info`,
      successUrl: `${config.get('SITE_URL')}/${req.params.owner}/${req.params.name}`,
      failUrl: `${config.get('SITE_URL')}/${req.params.owner}/${req.params.name}/v/${req.params.revisionId}`
    })
  }
})
```

**Comment by anuveyatsu** [comment]
FIXED

Full URL for SUCCEEDED revision: http://testing.datahub.io/core/finance-vix/v/37

For FAILED revisions you need to own a dataset to be able to view it, e.g.:
<img width="1280" alt="screen shot 2017-12-13 at 21 54 54" src="https://user-images.githubusercontent.com/17809581/33948526-4583fc06-e051-11e7-937e-18b559c4edad.png">

INPROGRESS revision:

<img width="1280" alt="screen shot 2017-12-13 at 15 27 33" src="https://user-images.githubusercontent.com/17809581/33948546-50baab6a-e051-11e7-9b36-a1483b21face.png">
