### ISSUE TITLE
When failed show which steps are failed

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#142]
As a Publisher I want to see why my dataset is failed so I can fix it and re-push.

## Acceptance criteria

* [x] when I visit specific revision's page with FAILED status, I can see what exactly is causing failure

## Tasks

* [x] refactor route to create an object with failed pipelines and pass it to the template
* [x] refactor template to include failed pipelines in the message box on the top of the page
* [x] add styles

## Analysis

Read the returned object from `info` api and access `pipelines` property and then iterate through it to find which pipelines are failed:

```javascript=
// in the route when status.state === 'FAIL':
let failedPipelines = []
for (var key in status.pipelines) {
  if (pipelines[key].status === 'FAIL') {
    failedPipelines.push(pipelines[key])
  }
}

// then pass failedPipelines object to template
```

and then in the template we need to show failed pipelines in the top of the page. It'd look like a list with light gray background that can be expanded to see error logs:

:::danger
\> Failed pipeline title 1
\> Failed pipeline title 2
:::

**Comment by anuveyatsu** [comment]
FIXED

<img width="1280" alt="screen shot 2017-12-13 at 12 12 09" src="https://user-images.githubusercontent.com/17809581/33924276-88864e98-dfff-11e7-9911-56e2e73e3f13.png">
