### ISSUE TITLE
Show validation errors for a resource

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#145]
As a Publisher I want to see validation reports for each of my resource in my dataset so I know what exactly is wrong in my data.

As a Consumer of data I want to see validation reports for each resource in dataset I'm intereseted in so I can assess its quality and can decide whether to use it.

Since we're receiving reports included in the processed datapackage.json, we want to display those validation reports to users.

## Acceptance criteria

* [x] I can clearly see validation reports on the showcase page for each resource

## Tasks

* [x] add tests
* [x] refactor showcase route to pass `report` object to the template
* [x] refactor showcase template
  * [x] add new empty divs before each preview table with `id="report-idx"`
  * [x] add script there that injects reports into that div using `goodtablesUI`
* [x] polish layout

## Analysis

Reports should be rendered in place of preview tables so there is enough space to display report tables. Also this place seems the most appropriate as reports will be just under the resource names.

Use `goodtales-ui` for rendering reports - https://github.com/frictionlessdata/goodtables-ui/blob/master/README.md

Using `goodtables-ui`:

In the showcase template:

```html=
<script src="//unpkg.com/goodtables-ui/dist/goodtables-ui.min.js"></script>

{% for resource in dataset.resources %}
...
<div id="report-{{loop.index - 1}}"></div>

<script>
  // `report` should be passed to the template
  var element = document.getElementById('report-{{loop.index - 1}}')
  goodtablesUI.render(goodtablesUI.Report, {report}, element)
</script>
...
{% endfor %}
```

Then we can add CSS from https://github.com/frictionlessdata/goodtables.io or use our own one.

**Comment by anuveyatsu** [comment]
FIXED

Validation report:

<img width="1280" alt="screen shot 2017-12-13 at 21 54 57" src="https://user-images.githubusercontent.com/17809581/33948230-971405b2-e050-11e7-9898-7ddf9b248c47.png">

Notice on top of the page:

<img width="1280" alt="screen shot 2017-12-13 at 21 54 54" src="https://user-images.githubusercontent.com/17809581/33948242-9cf2a2c2-e050-11e7-8151-904e4847c3d2.png">
