### ISSUE TITLE
http -> https redirection is not set.

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/frontend#146]
As an system admin, I want users to be redirected on the protected HTTPS version of datahub, so users are protected.

## Acceptance Criteria

* [x] When user goes on http://datahub.io/ he is automatically redirected to https://datahub.io

## Tasks

* [x] change the config on the server
* [x] check if the redirect is happens, when you go on http

## Analysis

* find the proper configuration file (nginx.conf?)

**Comment by Mikanebu** [comment]
@anuveyatsu Updated page rule on Cloudflare. Now, it always uses HTTPS. Please, review and close.

**Comment by anuveyatsu** [comment]
@Mikanebu great. Closing now as FIXED.
