### ISSUE TITLE
Short description 'what is data tool' on the docs main page.

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/frontend#147]
As a new user on the site, I want to know what is going on here, what tools can I use to reach my goals, so I will catch the main idea quickly, without lurking deeply in the docs.

## Acceptance Criteria

* [ ] When user goes on http://datahub.io/docs he could see short sentence, describing the tool that we use.

## Tasks

* [ ] discuss the text and got the Rufus acceptance on it
* [ ] change the title docs page.

**Comment by AcckiyGerman** [comment]
![what is data](https://user-images.githubusercontent.com/11707682/33765241-8dfff988-dc20-11e7-95db-012a3f473391.png)

**Comment by rufuspollock** [comment]
@AcckiyGerman why is this closed? Was it fixed?

**Comment by AcckiyGerman** [comment]
seems I close it accidentally , oops
