### ISSUE TITLE
Integrate filemanager (storage tracking)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#148]
As a Publisher I want to see how much of space I'm using in my dashboard so I have a sense of how much I may need to pay (or how much of free space is left).

As a User I want to see the size of a dataset that I'm looking at so that I have a sense of how much data is in it.

## Acceptance criteria

* [x] In my dashboard, I can see my total space usage
* [x] In showcase page, I can see size of the dataset

## Tasks

* [x] refactor `/dashboard` route
  * [x] hit filemanager API
  * [x] convert bytes to pretty bytes and pass to template
  * [x] render
* [x] refactor `/showcase` route
  * [x] hit filemanager API

**Comment by anuveyatsu** [comment]
FIXED - file manager is now used to display space usage in dashboard and on showcase pages.
