### ISSUE TITLE
Links for datapackage.json are broken for "old" datasets

### ISSUE THREAD

**Issue by zelima** [datahq/frontend#150]
After introducing data validation Feature and moving from `.../latest/mydata` to  `.../{revision-number}/mydatata` URLs. Old datasets that are not recently republished still live on `latest` so whenever requesting the latest successful revision for dataset we result in 404.

## Acceptance Criteria

* [x] No broken links for datapackage.json

## Tasks

option 1:
* [ ] republish all old datasets 
  * what about the ones that we don't own 

option 2:
* [x] check url before displaying -> if 404 -> construct another url with `latest`

**Comment by anuveyatsu** [comment]
FIXED, @zelima the latest commit delivers changes re your comment https://github.com/datahq/frontend/commit/74b3ce2f1e862af55625b70cce86788518ea3215#r26358764
