### ISSUE TITLE
Misc improvements on docs page

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#153]
We want to update and improve our installing and pushing data pages, so it deliver clear and updated message.

## Acceptance criteria

* [x] Installing data page is updated
* [x] Publishing a data page is updated
* [x] Tutorials section with tutorials on how to build graphs and visualizations

## Tasks

* [x] Installing data page
  * [x] add `chmod +x` command
  * [x] update link releases -> download page
* [x] Pushing a data file page
  * [x] add explanation for why csv?
  * [x] add login information prior pushing
  * [x] update output screenshot
  * [x] update `findability` information
  * [x] update screenshot for showcase page
  * [x] update screenshot for processing page
  * [x] rename pushing data -> publishing data
  * [x] There is no word about data should be valid?
    * [x] it should say it is going to validate your data and publish if everything is fine - otherwise you'd get validation errors
  * [x] `data push mydata.csv` should explain about path `data push pathToFile`
  * [x] add tutorials section
    * [x] add tutorials on how to build graphs and visualizations

**Comment by Mikanebu** [comment]
FIXED, now, we have a `tutorials` section in `docs` page and updated `publishing and installing data` pages
