### ISSUE TITLE
Redesign front page (outcome from UX/UI day)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#154]
As result of UX/UI analysis day on 26th Dec 2017, we have decided to redesign the front page:

* Main buttons below the fold!
* Get Started - with what?
* Terminal not clear
* Showcase not clear (only terminal has a shadow) - it does not look like showcase page so do we need it at all?
* Is it free?
* Why the separate alpha / sign-up message?
* What about the core datasets? 
* What are these tutorials? What are they doing in the main page? It’s ok cause no one will get to them anyway.
* Explore datasets -> search
* Our most popular, no popularity measures

## Acceptance criteria

* [x] when I visit front page, I can see nice explanation of how publishing happens

## Tasks

* [x] general redesigned of main page https://files.gitter.im/Datopian/datahub/r2Fw/IMG_20171226_110824.jpg
  * [x] On the left of the screen Create Gif showing
    * ls -> data.csv
    * `data push data.csv` -> progresbar -> copied to clipboard
    * ~~click on link and open browser~~
  * [x] On the right of the screen 3 main buttons (showing thee main features)
    * [x] Core Dataset 
    * [x] Request data
    * [x] Publish
  * [x] Say loudly it's Free! - 
    * not totally clear it is as I see only pricing page
  * [x] remove separate alpha / sign-up message below main buttons as it's outdated
  * [x] Remove Tutorials from main page and cores
    * there's no place for tutorials on main page
    * they are at the very bottom
  * [x] Rename Download button to "Publish data" 
    * it's confusing I thought it was for downloading datasets not application or tools

**Comment by anuveyatsu** [comment]
FIXED live now on production https://datahub.io
