### ISSUE TITLE
Add some explanation to the core and examples users

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#156]
We want to have some explanation to core and examples users, so it will give more info about the user

## Acceptance criteria

* [x] showcase for `core` user has an explanation `Core datasets, maintained by the datahub team`
* [x] showcase for `examples` user has an explanation `Examples datasets, maintained by the datahub team`

## Tasks 

* [x] update database for core and examples users
* [x] updated frontend page

**Comment by zelima** [comment]
FIXED live in testing
