### ISSUE TITLE
Download page rework (outcome from UX/UI day)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#158]
As we have discussed during the UX/UI analysis day, our current download page is confusing. It does not indicate clearly what users are going to download and doesn't provide any information about those tools.

## Acceptance criteria

* [x] when I arrive at download page, I can see a gif that explains how desktop app works (drag and drop)
* [x] I have information about what I can publish, how it works and how much it costs

## Tasks

* [x] Should be rethought as the 'Publish your Data' page:
  * [x] Should include a short explanation on how publishing data works on datahub:
    * [x] What you can publish?
    * [x] How does it work?
    * [x] How much does it cost?
  * [x] 'Desktop App' -> '`data` - our Publishing App'
    * [x] Remove reference to CLI tool
    * [x] Add some details about its features (e.g. validate? publish? etc.)
  * [x] 'Download data' -> Download `data`
  * [x] CLI Tool
    * [x] Revise wording: For advanced usages / users
    * [x] Show we can install via npm
    * [x] Not needed if already installed data desktop
    * [x] Need to include installation instructions here (e.g. copy to /usr/local/bin/data etc.)
  * [x] How to use the desktop app:
    * [x] Create a nice gif showing basic usage (drag a file onto the taskbar icon)
    * [x] Include a link to the blog post on that subject

**Comment by anuveyatsu** [comment]
FIXED and live in http://datahub.io/download
