### ISSUE TITLE
In dashboard page show public vs private datasets size information

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#165]
At the moment, we show total space usage by user, but it would be more informative to display how much of the space is used for private vs public datasets.

## Acceptance criteria

* [ ] when I arrive at my dashboard page, I can see space usage information about my private vs public/unlisted datasets

## Tasks

* [x] mockup [0.2h]
* [x] refactor the route so we get storage info about private and public/unlisted datasets [0.5h]
* [x] implement the mockup [0.5h]

## Analysis

Mockup:

<img width="746" alt="screen shot 2018-03-09 at 13 29 33" src="https://user-images.githubusercontent.com/17809581/37195667-003bbaa4-239e-11e8-99d7-8ce7a3a29676.png">

**Comment by anuveyatsu** [comment]
FIXED - not displaying the total amount of available space. It will be added once we have APIs.

<img width="789" alt="screen shot 2018-03-09 at 22 13 26" src="https://user-images.githubusercontent.com/17809581/37217217-294d4b26-23e7-11e8-9345-a7368ff90ed3.png">
