### ISSUE TITLE
Original data is not displayed in Failed and In progress stages

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#171]
When a revision is FAILED or INPROGRESS, we should have a preview of original data. However, this is not the case currently.

This also leads to another problem:

> there are resource names listed with download buttons and clicking them leads to 404

## Acceptance criteria

* [x] when revision is failed, I can see previews from original data
* [x] when revision is in progress, I can see previews from original data

## Tasks

* [x] analyse source of problem and possible solutions (1h)
* [x] plan the fix (0.5h)
* [x] implement (1.5h)

## Analysis

This issue needs to be considered for two cases: for pushing of local files, pushing of remote file and for push-flow.

**Pushing local files**

In this case, we upload files to AWS first so if we need to use the original data then we need to access it from AWS. Currently, we are using original dp.json from source spec as in the links below. Resource objects there have local paths that cannot be rendered in the frontend. We need to use paths in AWS instead:

FAILED:
https://github.com/datahq/frontend/blob/master/routes/index.js#L413

INPROGRESS:
https://github.com/datahq/frontend/blob/master/routes/index.js#L456

If we take a look at source spec, we can see that there is `resource-mapping` property that gives us information about URLs in the AWS that can be used when rendering showcase page for FAILED and INPROGRESS stages:

```
"spec_contents": {
    "inputs": [
      {
        "kind": "datapackage",
        "parameters": {
          "descriptor": {
            "name": "finance-vix",
            "readme": "...",
            "resources": [
              {
                "format": "csv",
                "mediatype": "text/csv",
                "name": "vix-daily",
                "path": "data/vix-daily.csv",
                "schema": {...}
              }
            ],
            "sources": [...]
          },
          "resource-mapping": {
            "data/vix-daily.csv": "https://s3.amazonaws.com/rawstore.datahub.io/9c46b3948d297fa1c4e92ead714f0399.csv"
          }
        },
        "url": "https://s3.amazonaws.com/rawstore.datahub.io/7564a3f403a417cd6cb98c6166177807.json"
      }
    ],
    "meta": {
      ...
    }
  }
```

**Pushing remote file**

When we push remote file it has `path` property set to user-provided URL which just can be used to render the original data. However, our `showcase-js` library expects `views` property in the descriptor to have `preview` views to render any tables. This is also applicable for other cases when we push local files and push-flow.

The workaround here would be to generate a preview view prior to rendering the page:

```javascript
// frontend code - routes.js
normalizedDp.views = normalizedDp.views ? normalizedDp.views : []
normalizedDp.resources.forEach(resource => {
  let view = {
    "datahub": {
      "type": "preview"
    },
    "resources": [
       resource.name
    ],
    "specType": "table"
  }
})
```

**push-flow**

Here we only have user-provided URL to data - if this URL can be rendered (e.g., it is CSV) then OK, but if it is excel we won't be able to render it.

**Comment by anuveyatsu** [comment]
FIXED - now we render views and previews while revision is INPROGRESS or FAILED using original data from AWS.

INPROGRESS:
<img width="1280" alt="screen shot 2018-01-19 at 13 07 14" src="https://user-images.githubusercontent.com/17809581/35143219-1c3e488c-fd2b-11e7-9180-98227bcaa1c1.png">


FAILED:
<img width="1280" alt="screen shot 2018-01-19 at 13 07 23" src="https://user-images.githubusercontent.com/17809581/35143221-21332c72-fd2b-11e7-9bce-66fbcf449766.png">
