### ISSUE TITLE
README is not shown while revision is FAILED or INPROGRESS

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#172]
When a revision is FAILED or INPROGRESS, a showcase page does not include README section, although a dataset has it.

If there is no README then just don’t have "Read me" heading.

## Acceptance criteria

* [x] readme is included in a showcase page, when revision is FAILED or INPROGRESS

## Tasks

* [x] analyse the source of the problem and possible solutions
* [x] plan out implementation
* [x] implement

## Analysis

* How do we render the readme?
  * we have two versions of readme on showcase page: short readme on top of the page and full readme in the bottom
  * short readme: `{{dataset.readmeSnippet}}`
  * full readme: `{{dataset.readmeHtml|safe}}`

If state of revision is FAILED or INPROGRESS, we use original dp.json from source api. This descriptor only has `readme` property written in markdown. We want to include processed `readmeSnippet` and `dataset.readmeHtml` properties to be able to display the showcase page with readme information.

**Comment by anuveyatsu** [comment]
FIXED - now short readme and full readme in html is included when rendering the showcase page using original dp.json:

<img width="1196" alt="screen shot 2018-01-19 at 15 13 03" src="https://user-images.githubusercontent.com/17809581/35143291-5c8c77f6-fd2b-11e7-8e4d-c4966fad9054.png">
