### ISSUE TITLE
General styling improvements on showcase page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#173]
* error message on the top should have some RED colour, e.g, we can make borders red so publishers pay enough attention to reading it
* Unlisted has badge, but private and public does not
* there is a lag between processing steps
  * we should have the main spinner that always spins to indicate process is still on
* there are lots of other errors that are not helping me in fixing the actual problems, e.g., I don’t need to see “Dependency unsuccessful” error
* several "Creating CSV" errors - some are useful, some are just empty [investigate]

## Acceptance criteria

* [x] all points above are fixed

## Tasks

* [x] apply red borders for error message boxes on the top of the page [10m]
* [x] add "private" badge for private datasets (same way as for "unlisted") [10m]
* ~~implement the main spinner while in progress stage [20m]~~
* [x] hide "Dependency unsuccessful" errors and empty errors on FAILED stage [20m]

**Comment by anuveyatsu** [comment]
FIXED, decided to not implement the main spinner as it does not look good. Other items are covered and fixed.
