### ISSUE TITLE
Indicate exactly which resource is processed  

### ISSUE THREAD

**Issue by zelima** [datahq/frontend#178]
When I have several resources, there are identical steps “Creating CSV/JSON” which does not make lots of sense Eg https://i.imgur.com/yZ3ginK.png. Would be good to indicate which exact resource is being processed

## Acceptance Criteria

* [x] Know exactly which resource is being processed when looking at revision process

## Tasks

* [x] do analysis
* [x] pass `resources` object to `uploading` snippet and implement filtering by resource prefix in pipeline name
* [x] implement grouping/placing correctly on the page + apply CSS

## Analysis 

> we could clear succeeded steps (especially those that are repetitive) so we don't have a very long list of pipelines https://i.imgur.com/yZ3ginK.png - and we could change the main message on top indicating which resource is being processed

It will be hard to have message on top indicating which resource is being processed as we process resources in parallel and we might have multiple `Creating CSV` simultaneously, therefore no sense of saying which resource is currently processed

I see two option here: 
1. Include resource name when displaying processing info Eg `Creating CSV ({my-awsome-resource})` or `Creating CSV for {my-awsome-resource}` and delete once done
2. have them grouped under resource. name something like this and keep everything:
```
my-resource-1          my-resource-2          my-resource-3 
 ✓ Creating CSV         ✓ Creating CSV         ...
 ✓ Creating JSON        ✓ Creating JSON
 ✗ Creating Preview     ✓ Creating Preview

rest
 ✗ Creating ZIP        
 ✗ Creating Package
```

I recommend the second option. Several reasons:
* In case of failed processors the first option would still list too many of them
* more readable and searchable for humans 
* Full history is there (no deleted processing)
* maybe gives the ability to have a progress bar (??)
* ...

**Comment by anuveyatsu** [comment]
FIXED:

<img width="1280" alt="screen shot 2018-01-24 at 15 30 38" src="https://user-images.githubusercontent.com/17809581/35325299-823c0494-011d-11e8-9d6d-912cb7bbb03d.png">
