### ISSUE TITLE
Some validation errors are not being identified

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#191]
Reported here: datahq/datahub-qa#68

We want to improve showcase page, so it should have error messages as per readme of the dp, eg, when pushing following datapackages some errors are not catched in the frontend:

https://github.com/frictionlessdata/test-data/tree/master/packages/types-formats-and-constraints

* `string` - The value “https:/domain.com” in column “uri” is not type “string” and format “uri”
* `datetime` - The value “2018/01/02T00:00:00” in column “any” is not type “datetime” and format “any”
* `time` - The value “00:01” in column “any” is not type “time” and format “any”

## Acceptance criteria

the dataset page should have error messages on showcase page as per readme of the dp:
* [x] `string` - The value “https:/domain.com” in column “uri” is not type “string” and format “uri”
    - WONTFIX: https://github.com/datahq/frontend/issues/191#issuecomment-370723362
* [x] `datetime` - The value “2018/01/02T00:00:00” in column “any” is not type “datetime” and format “any”
    - WONTFIX: https://github.com/datahq/frontend/issues/191#issuecomment-370764258
* [x] `time` - The value “00:01” in column “any” is not type “time” and format “any”
    - WONTFIX:  '00:01' is not time? :face_with_head_bandage:  Really?!! Who's that guy, who created the corresponding test?

## Tasks

* [ ] add tests for `tableschema-py`
* [ ] fix `tableschema-py`

## Analysis
- `data validate` uses `tableschema-js` and found all errors
- server users `tableschema-py` and NOT found some errors

### How to reproduce
1. `data validate` and remember errors
2. `data push` and see errors on the dataset page

- string:
`$ data validate test-data/packages/types-formats-and-constraints/string/`
`$ data push test-data/packages/types-formats-and-constraints/string/`

- datetime:
`$ data validate test-data/packages/types-formats-and-constraints/datetime/`
`$ data push test-data/packages/types-formats-and-constraints/datetime/`

- time: 
`$ data validate test-data/packages/types-formats-and-constraints/time/`
`$ data push test-data/packages/types-formats-and-constraints/time/`

**Comment by AcckiyGerman** [comment]
## WONTFIX: String validator accept `http:/datahub.io` uri

The difference between JS and Python versions of `tableschema` about validating URI is:
- tableschema-js uses `"validator": "^9.2.0"` from npm
- tableschema-py uses https://pypi.python.org/pypi/rfc3986

AND
- http:/datahub.io is NOT VALID for npm `validator`
- http:/datahub.io is VALID for pypi `rfc3986`

When I goes deeper I realized that there is an ANCIENT & GREAT HOLY WAR called:
**Accept or not Accept an URI with less or more than two `//` separators**:
> https://daniel.haxx.se/blog/2016/05/11/my-url-isnt-your-url/
The WHATWG spec says it has to be one slash and that a parser must accept an indefinite amount of slashes. “http:/example.com” and “http:////////////////////////////////////example.com” are both equally fine. RFC 3986 and many others would disagree.

Also, most of browsers accept  `http:/datahub.io` uri - I just have checked.

So the pypi [implementation of rfc3986](https://pypi.python.org/pypi/rfc3986) DOES accepts this kind of invalid URI;
And I doubt that @roll will accept any PR where we will implement URI validator by ourselves, just for fixing this particular edge case.

Also, the URI validating REGEX is so f**king complex:
```regex
/
# protocol user host-ip port path path path querystring fragment
^
#protocol
(?:(?<scheme>[a-zA-Z][a-zA-Z\d+-.]*):)?
(?:
  (?:
    (?:
        \/\/
        (?:
            #userinfo
            (?:((?:[a-zA-Z\d\-._~\!$&'()*+,;=%]*)(?::(?:[a-zA-Z\d\-._~\!$&'()*+,;=:%]*))?)@)?
            #host-ip
            ((?:[a-zA-Z\d-.%]+)|(?:\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3})|(?:\[(?:[a-fA-F\d.:]+)\]))?
            #port
            (?::(\d*))?
        )
    )
    #slash-path
    (
        (?:\/[a-zA-Z\d\-._~\!$&'()*+,;=:@%]*)*
    )
  )
 #slash-path
 |(\/(?:(?:[a-zA-Z\d\-._~\!$&'()*+,;=:@%]+(?:\/[a-zA-Z\d\-._~\!$&'()*+,;=:@%]*)*))?)
 #path
 |([a-zA-Z\d\-._~\!$&'()*+,;=:@%]+(?:\/[a-zA-Z\d\-._~\!$&'()*+,;=:@%]*)*)
)?
#querystring
(?:\?([a-zA-Z\d\-._~\!$&'()*+,;=:@%\/?]*))?
#fragment
(?:\#([a-zA-Z\d\-._~\!$&'()*+,;=:@%\/?]*))?
$
/x
```
So I'm leaving this URI validator as it is.

**Comment by AcckiyGerman** [comment]
## WONTFIX: `tableschema-py` validator accepts datetime `2018/01/02T00:00:00` format: Any

This `2018/01/02T00:00:00` is a
- Valid date due to python lib
```python
>>> from dateutil.parser import parse
>>> parse("2018/01/02T00:00:00")
datetime.datetime(2018, 1, 2, 0, 0)
```
- Invalid date due to JS libs
```node
> moment = require('moment')
> moment("2018/01/02T00:00:00")
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions.
```

**Comment by AcckiyGerman** [comment]
FIXED:
`JS` version of `tableschema` gives some validation errors, while `PY` version doesn't:
- `00:01` is not Time
- `"2018/01/02T00:00:00"` is not datetime with format 'Any'
- `http:/datahub.io` is not correct URI
(I agree with the last one, but developers of rfc3986 validator lib for Python are not agree)

So, everything is good with our Pipeline.
- If we think that `00:01` is valid time format - we should fix `tableschema-js` (and `data validate`) instead.
- If we think that `00:01` is invalid time format - then we should validate a dataset prior pushing, coz `tableschema-py` Authors will not accept such a change anyway.

And I'm going to change the corresponding QA test.
