### ISSUE TITLE
Instructions for importing data are not working

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#197]
* As a User I want to import data from datahub into my favourite language so I can work with it on my project.
  * As a User I want to import particular data (resource) from datahub so I get only what I need to work on my project.
  * As a User I want to import all data (resources) from datahub so I can start working with them on my project.

Reported here: https://github.com/datahq/datahub-qa/issues/49

We cannot use data from the datahub following the instruction

## Acceptance criteria

* [x] All examples in instructions section are working fine
    - [x] R
    - [x] Pandas
    - [x] Python
    - [x] JavaScript
    - [x] Ruby - removed
* [x] instructions on http://datahub.io/blog/core-data-essential-datasets-for-data-wranglers-and-data-scientists is updated
* [x] blogpost `how to use datapackages from R` http://datahub.io/blog/how-to-use-data-packages-from-r is updated
* [x] docs on `getting-data` http://datahub.io/docs/getting-started/getting-data is updated

## Tasks

* [x] Test and update the following languages in instructions section
    - [x] R
    - [x] Pandas
    - [x] Python
    - [x] JavaScript
    - [x] Ruby -removed due to errors
* [x] update blogpost instructions http://datahub.io/blog/core-data-essential-datasets-for-data-wranglers-and-data-scientists
* [x] update blogpost `how to use datapackages from R` http://datahub.io/blog/how-to-use-data-packages-from-r
* [x] update docs on `getting-data` http://datahub.io/docs/getting-started/getting-data

### How to reproduce

Go to any dataset page on the datahub.io and try to use the dataset due to instructions, e.g. http://datahub.io/core/cofog#python

### The current status:

* Pandas

python 2.7 and 3.6 
```
tableschema.exceptions.DataPackageException: Unable to load JSON at "http://datahub.io/zelima/basic-csv/datapackage.json"
```

Casting error happens if I use this library from https://github.com/frictionlessdata/tableschema-pandas-py

```
  File "/Users/Zhiyenbayev_mirza/anaconda3/lib/python3.6/site-packages/tableschema/schema.py", line 152, in cast_row
    raise exceptions.CastError(message, errors=errors)
tableschema.exceptions.CastError: There are 5 cast errors (see exception.errors)
```

* Python

Update path to resource `data = package.resources[1].read()`.
Currently, it is pointing to validation report resource

We cannot use a particular index to get data, so we need to retrieve data from identifying `type` of a file. For example, some datasets, they do not have a `validation_report` resource, meaning that we cannot use our `package.resources[1]`, it will point to `JSON` version of the file. This is the optimal solution to get `CSV` data:

```
if (resourseTypeList[x]['type'] == 'derived/csv'):
```

* Javascript 

```
(async () => {
^

TypeError: "http://datahub.io/zelima/basic-csv/datapackage.json" is not a function

^^^ you forgot to import Dataset probably

[anu]: we should think how to give resource index correctly not just [0]... also need to print data in the end so users copy-paste and get data on their screen
```

This snipped for JS works fine, only need to add `;` in the beginning of the function according to the https://github.com/babel/babel/issues/7172

* Ruby
  * redirection error: ruby is not allowing redirection when trying to read dp.json
  * once dp.json is read, in instructions we suggest reading [0] resource but it is pointing to dp report which cannot be read because not tabular

This package does not work for any type of resource: https://github.com/frictionlessdata/datapackage-rb
```
InvalidFormat: The format `%Y-%m-%d` is not supported by the type ``
```

```
TableSchema::InvalidDateType: Date is not a valid date
```

* R

Update path to resource `path_to_file = json_data$resources$path[1][1]`.
Currently, it is pointing to validation report resource

Again, same problem as with Python part, so this is snippet to check `type` of file 
```
for(i in 1:length(json_data$resources$datahub$type)){
  if(json_data$resources$datahub$type[i]=='derived/csv'){
    path_to_file = json_data$resources$path[i]
  }
}
```

**Comment by Mikanebu** [comment]
We decided to remove Ruby instructions since it was a lots of issues with `date` type. For example 
```
InvalidFormat: The format `%Y-%m-%d` is not supported by the type `
```
That's why it fails for some datasets. 

And we are planning to replace it with `cURL `. But, in tutorial it lists only list of resources, but it needs more time to follow our common algorithms which includes printing all tabular files.

**Comment by AcckiyGerman** [comment]
TESTED: Failed
https://github.com/datahq/datahub-qa/issues/49#issuecomment-364008767

**Comment by Mikanebu** [comment]
FIXED, updated instruction for R, python, pandas, javascript. Since we have a lot of issue with `Ruby`, we decided to remove ruby instruction. Also, updated docs on getting data tutorial, and blog posts `how to use datapackages from R` and `core data essential datasets for data wranglers and data scientists`
