### ISSUE TITLE
Showcase page crashes when tries to show a preview for a big file.

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/frontend#198]
Part of this issue: https://github.com/datahq/datahub-qa/issues/62

After `data push <168mb.csv>` the processing page is trying to create a preview table.
I could see my browser downloads a ~160mb of traffic from the server and then browser page crashes.
Tested in Chrome version 64.0.3282.140
Broken preview page: https://datahub.io/AcckiyGerman/big-168-wide-10000/v/1

## Acceptance Criteria

* [x] while in progress or failed, showcase page does not crash due to overload
  * [x] we show users a placeholder saying that all views will be available/visible once data is processed
* [x] succeded showcase page works as before

## Tasks

* [x] refactor logic in the templates for FAILED and INPROGRESS showcase page:
  * [x] if SUCCEEDED load bundle.js and render the page as usual
  * [x] if FAILED or INPROGRESS, do not load bundle.js but iterate through "react-me" elements and put placeholder saying that all views will be available once data is processed
* [x] apply stylings so placeholders look match overall DataHub style 

## Analysis

In the dev-tools I could see that browser successfully loads the data before crashing.
I assume that we use the original data to render a preview while server side is processing/fail dataset. So when data is huge - browser crashes.

This preview is rendered on the 'processing' or 'fail' pages.

### Possible solutions:

* fetch the file head and if `file.size > 1mb` then show `sorry this file is too big for preview`
* set-up the stream and fetch only the first rows (1k is enough) for preview, if there are more - disconnect
* set-up the stream and create an 'infinity-scroll' which will fetch and render new rows, when user scroll the table.
* **page not shows the preview while the background is processing data.** This variant was chosen after team discussion

> @anuveyatsu 
>  in my opinion, we should just fetch head and if size is more than 2-3MB then render nice message asking user to wait until we finish processing.

> @zelima Why not display that message in any case?

**Comment by AcckiyGerman** [comment]
> @anuveyatsu 
>  this is where fetching data happens in the frontend-showcase-js: https://github.com/datahq/frontend-showcase-js/blob/gh-pages/src/index.jsx#L101

**Comment by akariv** [comment]
I think the solution should be here:
Preview table (and other views) should only be displayed when/if the required derived resources are done and ready.
While data is processing we don't show previews.

**Comment by anuveyatsu** [comment]
FIXED, e.g., tested on dataset that's original data is ~171MB
