### ISSUE TITLE
Convert tests from Mocha to Ava

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#20]
At the moment, we are using `Mocha` test framework for tests in this library. For consistency, we have decided to convert all tests to `Ava`.

## Acceptance criteria

* [x] all tests written using `Ava`

## Tasks

* [x] update packages.json, add ava instead of mocha
* [x] add watch:test
* [x] update all tests with ava

## Analysis

Mocha [source](https://mochajs.org/)
Ava [source](https://github.com/avajs/ava)
Supertest [source](https://github.com/visionmedia/supertest)
Supertest for ava [source](https://github.com/avajs/ava/blob/master/docs/recipes/endpoint-testing.md)

**Comment by Mikanebu** [comment]
FIXED
