### ISSUE TITLE
Showcase page for dataset with invalid data behaves unexpectedly

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#206]
As described in https://github.com/datahq/datahub-qa/issues/102 some invalid datasets are causing errors when rendering showcase page. If I push https://github.com/frictionlessdata/test-data, after processing succeeded the showcase would fail to load. By taking a look at the logs I see the following:

```
[frontend-1]2018-02-12T13:38:18.647670744Z TypeError: Cannot read property 'name' of null

[frontend-1]2018-02-12T13:38:18.647705171Z     at good.resources.forEach.res (/frontend-app/lib/index.js:320:19)

[frontend-1]2018-02-12T13:38:18.647712294Z     at Array.forEach (native)

[frontend-1]2018-02-12T13:38:18.647718807Z     at Function.makeGoodDp (/frontend-app/lib/index.js:318:21)

[frontend-1]2018-02-12T13:38:18.647724636Z     at DataHubApi.getPackage (/frontend-app/lib/index.js:62:27)

[frontend-1]2018-02-12T13:38:18.647730472Z     at process._tickCallback (internal/process/next_tick.js:109:7)
```

## Acceptance criteria

* [x] this showcase page is loaded correctly https://datahub.io/anuveyatsu/basic-csv/v/11

## Tasks

* [x] investigate what is causing the error
* [x] refactor frontend code to handle this case

## Analysis

This is happening because processed dp.json for some reason is not generating derived CSV and JSON resources for one of the original resources: https://s3.amazonaws.com/pkgstore.datahub.io/90998f7f90e086bd5fc7c9075dfda43b/basic-csv/11/datapackage.json

Due to that fact, our function that converts "extended" dp.json into "logical" one, cannot find derived CSV for the original resource and appends `null` to the array of logical resources. This then causes the exception that we see in the logs: `TypeError: Cannot read property 'name' of null`.

To fix this, we need to refactor `extendedToLogical` function in `/lib/index.js` so in case there is no derived CSV version for the original resource, it just appends the original resource itself to the logical array of resources:

```javascript
static extendedToLogical(extended) {
  ...
  if (newResource) {
     newListOfResources.push(newResource)
  } else {
     newListOfResources.push(original)
  }
  ...
}
```

**Comment by anuveyatsu** [comment]
@zelima can you please take a look why there is no derived CSV/JSON for one of the two resources, although the revision is succeeded - https://s3.amazonaws.com/pkgstore.datahub.io/90998f7f90e086bd5fc7c9075dfda43b/basic-csv/11/datapackage.json
For more details please read analysis section of this issue.

**Comment by anuveyatsu** [comment]
FIXED - see this showcase page working https://datahub.io/anuveyatsu/basic-csv/v/11
