### ISSUE TITLE
Repeating dates in the x axis of the simple graphs

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#207]
As described in https://github.com/datahq/datahub-qa/issues/111 the graph in https://datahub.io/AcckiyGerman/datahub-qa-issues-tracker looks wrong.

## Acceptance criteria

* [x] this looks correct with no repeating values https://datahub.io/AcckiyGerman/datahub-qa-issues-tracker

## Tasks

* [x] investigate the source
  * [x] try it out in the Plotly editor (e.g., codepen)
* [x] refactor function that converts simple spec to plotly spec
* [x] update `datapackage-render-js` => `frontend-showcase-js` => `frontend`
* [x] deploy changes

## Analysis

We're using Plotly library to render simple graphs and conversion of simple spec to plotly spec is happening here https://github.com/frictionlessdata/datapackage-render-js/blob/master/lib/view.js#L71-L82

Looking at documentation on https://plot.ly/javascript/reference/#layout-xaxis-tickmode it seems like we need to set `tickmode` option to `linear`. By default, it is using `array` mode and as there are very few values in the data array, it's repeating them. The workaround here would be to use `linear` mode in the layout object:

```javascript
const plotlySpec = {
    data
    , layout: {
      title: view.title ? view.title : ''
      , height: 450
      , xaxis: {
        title: view.spec.group
        , tickformat: xAxisField.type === 'date' ? "%e %b %Y" : ''
        , type: dateFields.includes(xAxisField.type) ? 'date' : xAxisField.type
        , tickmode: 'linear'
      }
    }
  }
```

The same approach can be used for y axis:

```javascript
...
, yaxis: {
  tickmode: 'linear'
}
...
```

**Comment by anuveyatsu** [comment]
FIXED, see https://datahub.io/AcckiyGerman/datahub-qa-issues-tracker you may need to clear cached bundle.js (or just open in incognito mode)
