### ISSUE TITLE
Instructions for R is failing on Linux

### ISSUE THREAD

**Issue by zelima** [datahq/frontend#209]
Originally comes from here https://github.com/datahq/datahub-qa/issues/115

You might get following error if you're using Linux 
```
Warning in install.packages("jsonlite") :
  'lib = "/usr/local/lib/R/site-library"' is not writable
Error in install.packages("jsonlite") : unable to install packages
```

## Acceptance Criteria 

* [ ] Following the Instructions on datahub/publisher/package for R should print data

## Tasks 

* [ ] find the reason
* [ ] update the isntrutions 

## Analysis

Following this blog post https://www.r-bloggers.com/installing-r-packages/ 

> `install.packages("jsonlite")`
> In theory the package should just install, however:
> * if you are using Linux and don’t have root access, this command won’t work.
> * you will be asked to select your local mirror, i.e. which server should you use to download the package.

This issue is fixed if you try and run scripts with root permission. However, I'm getting following
```
Error in contrib.url(repos, type) : 
  trying to use CRAN without setting a mirror
```

No errors are produced  if you specify package repository. For instance, this works perfectly if you run with sudo

```
install.packages("jsonlite", repos="https://cran.rstudio.com/")
library("jsonlite")

json_file <- 'https://datahub.io/core/finance-vix/datapackage.json'
json_data <- fromJSON(paste(readLines(json_file), collapse=""))

# get list of all resources:
print(json_data$resources$name)

# print all tabular data(if exists any)
for(i in 1:length(json_data$resources$datahub$type)){
  if(json_data$resources$datahub$type[i]=='derived/csv'){
    path_to_file = json_data$resources$path[i]
    data <- read.csv(url(path_to_file))
    print(data)
  }
}

```
