### ISSUE TITLE
Sort data rows before rendering a graph

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#211]
As described here https://github.com/datahq/datahub-qa/issues/124 if rows are unordered, the graph is not correctly rendered. We want to add small sorting logic prior to rendering that wouldn't have an impact on performance (e.g., we can sort rows only if the length is less than 1000).

## Acceptance criteria

* [x] the graph here is rendered correctly 
  * [x] https://datahub.io/core/population-global-historical
  * [x] https://datahub.io/core/household-income-us-historical

## Tasks

* [x] refactor datapackage-render-js library so in `simpleToPlotly` function we do sorting
* [x] re-build frontend-showcase-js
* [x] deploy changes

**Comment by anuveyatsu** [comment]
FIXED see https://datahub.io/core/population-global-historical and https://datahub.io/core/household-income-us-historical
