### ISSUE TITLE
Some data types are not rendered as expected on showcase page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#213]
As a Publisher, I want to see raw data in the preview tables without any conversions so I know how exactly data looks like before downloading/working with it.

As described in https://github.com/datahq/datahub-qa/issues/131, user provided raw data is being converted while rendering on showcase page.

## Acceptance criteria

* [x] the preview table renders raw data in https://datahub.io/anuveyatsu/all-schema-types

## Tasks

* [x] analysis and investigations
  * [x] reproduce running showcase-js and dp-render-js libraries locally to find the source of conversions
  * [x] think of the best way of resolving it
* [x] implement the fixes
* [x] deploy frontend

**Comment by anuveyatsu** [comment]
FIXED, see https://datahub.io/anuveyatsu/all-schema-types
