### ISSUE TITLE
Ability to add (append) tick suffix to graph axis

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#216]
As a Publisher, I want to be able to add a suffix to the graph axis so my numbers are represented correctly.

This issue is reported here https://github.com/datahq/datahub-qa/issues/133

## Acceptance criteria

* [x] I can have tick suffixes in simple graphs
* [x] documented in http://datahub.io/docs/features/views

## Tasks

* [x] refactor `datapackage-render-js` library to handle suffix property in the simple spec
* [x] test out and rebuild showcase-js
* [x] add docs
* [x] deploy

**Comment by anuveyatsu** [comment]
FIXED, see https://datahub.io/anuveyatsu/simple-views and its views property https://pkgstore.datahub.io/90998f7f90e086bd5fc7c9075dfda43b/simple-views/3/datapackage.json
