### ISSUE TITLE
Custom axis titles in the graphs

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#217]
As a Publisher, I want to customize x and y axis titles so my graph looks more informative.

Reported in https://github.com/datahq/datahub-qa/issues/134

## Acceptance criteria

* [x] I can set my titles for x and y axis in the views
* [x] there is some explanation in docs - http://datahub.io/docs/features/views#how-it-works

## Tasks

* [x] refactor `datapackage-render-js` library to handle `xTitle` and `yTitle` properties in the spec
* [x] test and rebuild bundle.js in `showcase-js`
* [x] add docs
* [x] deploy

**Comment by anuveyatsu** [comment]
FIXED, see the graph on https://datahub.io/anuveyatsu/simple-views and take a look at its views in descriptor https://datahub.io/anuveyatsu/simple-views/datapackage.json

The docs are in http://datahub.io/docs/features/views#how-it-works
