### ISSUE TITLE
Add pagination on the publisher's page

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#218]
This issue reported here https://github.com/datahq/datahub-qa/issues/84
We want to add pagination to publishers page, so all datasets will be displayed.

## Acceptance criteria

* [x] pagination is added to publishers page when datasets > 20

## Tasks

* [x] move `pagination` function to `/lib/utils` so we can re-use it here
* [x] copy over route logics from search page to publisher page
* [x] copy over with some refactorings the template part for pagination from `search.html`
* [x] fix tests

**Comment by Mikanebu** [comment]
FIXED, now we have a pagination for `publisher` page
