### ISSUE TITLE
GeoJSON resources should render maps

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#220]
Reported in https://github.com/datahq/datahub-qa/issues/146

## Acceptance criteria

* [x] this dataset renders a map in the preview section - http://datahub.io/examples/geojson-tutorial

## Tasks

* [x] analysis in `datapackage-render` and `showcase-js` libraries
* [x] refactor `showcase-js` so `geojson` resources are added into `resourcesForPreview` list
* [x] refactor frontend so indexes of the resources are keeped

## Analysis

Rendering maps from `geojson` files happens in `showcase-js` and it was disabled since the last refactoring of backend: preview views are now rendered depending on the existence of "preview" view objects in the `dp.views` property. But we now want to render a leaflet map for each resource that has `format === geojson` by default.

Looking at `showcase-js` code we see that all we need to do is to add `geojson` resources into `resourcesForPreview` list.

**Comment by anuveyatsu** [comment]
FIXED - http://datahub.io/examples/geojson-tutorial
