### ISSUE TITLE
Split docs + blog as a separate repo (just like awesome pages) (datahq/content)

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#223]
Reported here https://github.com/datahq/datahub-qa/issues/156
We want to split out docs & blog as a separate repo, so users will be able to contribute. 

## Acceptance criteria

* [x] docs as a separate repo on `datahg/content`

## Tasks

* [x] proper analysis
* [x] create a repo `content` and move `docs` directory there
* [x] refactor routes for `/docs`
* [x] move docs related assets into `content` repo

## Analysis

There are 2 parts of work here:

#### /blog
In order to implement main blog page, we can use GitHub API https://developer.github.com/v3/repos/contents/#get-contents to get  all blogposts and other related properties like `url`, `name` etc

Instead of iterating through `blog` directory, we can iterate using https://api.github.com/repos/datahq/frontend/contents/blog

We need to refactor this part using GitHub API 
```
 router.get('/blog', (req, res) => {
    const listOfPosts = []
    fs.readdirSync('blog/').forEach(post => {
      const filePath = `blog/${post}`
      const text = fs.readFileSync(filePath, 'utf8')
      let parsedWithFM = fm(text)
      parsedWithFM.body = utils.md.render(parsedWithFM.body)
      parsedWithFM.attributes.date = moment(parsedWithFM.attributes.date).format('MMMM Do, YYYY')
      parsedWithFM.attributes.authors = parsedWithFM.attributes.authors.map(author => authors[author])
      parsedWithFM.path = `blog/${post.slice(11, -3)}`
      listOfPosts.unshift(parsedWithFM)
    })
    res.render('blog.html', {
      title: 'Home',
      posts: listOfPosts
    })
  })
```
#### /blog/:post

For each blog post we can take a look on the function which generates `awesome-pages` and refactor it to our needs
```
  async function showAwesomePage(req, res) {
    const BASE = 'https://raw.githubusercontent.com/datahubio/awesome-data/master/'
    const path = req.params.page ? req.params.page + '.md' : 'README.md'
    //request raw page from github
    let gitpath = BASE + path
    let editpath = 'https://github.com/datahubio/awesome-data/edit/master/' + path
    const resp = await fetch(gitpath)
    const text = await resp.text()
    // parse the raw .md page and render it with a template.
    const parsedWithFrontMatter = fm(text)
    res.render('awesome.html', {
      title: parsedWithFrontMatter.attributes.title,
      page: req.params.page,
      editpath: editpath,
      description: parsedWithFrontMatter.attributes.description,
      content: utils.md.render(parsedWithFrontMatter.body)
    })
  }
```

### Docs section

We have to refactor showDoc function https://github.com/datahq/frontend/blob/4eb54e021af7742a419ff12662a83f161803ba61/routes/index.js#L255

We can generate url using similar logic as in `awesome pages` by using `showAwesomePage` function or GitHub API again, WDYT @anuveyatsu?

**Comment by Mikanebu** [comment]
FIXED, now we have docs and related assets moved in https://github.com/datahq/content. But, we kept `blog` here.
