### ISSUE TITLE
API Documentation (GET&POST) + CURL instructions on showcase page

### ISSUE THREAD

**Issue by AcckiyGerman** [datahq/frontend#224]
[Original issue in datahub-qa](https://github.com/datahq/datahub-qa/issues/157)

As a programmer I want to have proper docs re using datahub API so I could use it in my project

## Acceptance criteria

* [x] Review from Irakly or Anu

## Tasks
Write an article[s] in hackmd
* [x] document Web API for getting data and datasets
  - [x] /r/ links ... 
  - [x] datapackage.json
* [x] Web API for creating datasets and pushing data
* [x] curl and `data get` instructions on the showcase page

Get a review
- [x] review from @zelima or @anuveyatsu 

Update the docs:
- [x] docs section on datahub.io
- [x] getting data section on the dataset's showcase page

**Comment by AcckiyGerman** [comment]
Adding more fixes: https://github.com/datahq/datahub-qa/issues/157#issuecomment-373139268

**Comment by anuveyatsu** [comment]
FIXED
