### ISSUE TITLE
FIilter datasets by findability on publishers page 

### ISSUE THREAD

**Issue by zelima** [datahq/frontend#225]
Originally coming from here https://github.com/datahq/datahub-qa/issues/154

We need to filter page by findability. Eg I'm interested to see only private datasets of mine

## Acceptance Criteria

* [ ] Able to type private and get datasets (maybe like github search?)
* [ ] or alternatively dropdown

## Tasks

* [ ] do analysis and decide on solution
* [ ] implement
