### ISSUE TITLE
[showcase] Improve UX of Copy (to clipboard buttons)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#237]
As reported in https://github.com/datahq/datahub-qa/issues/168

## Acceptance criteria

* [x] copy button content is a nice "copy" icon
* [x] if I hover that button, I'd see a hint saying "Copy to clipboard" so I understand what this button does
* [x] when I click on the button and the snippet is copied to the clipboard, I can see a hint saying "Copied" so I know it's know copied

## Tasks

* [x] refactor `frontend-showcase-js` to have a hover listener, eg, use https://www.npmjs.com/package/react-hover
* [x] refactor `CopyToClipboard` component so it triggers hover text change when the snippet is in clipboard
* [x] add styles in frontend repo to display changes appropriately
* [x] deploy

**Comment by anuveyatsu** [comment]
FIXED, e.g., see https://datahub.io/core/finance-vix
