### ISSUE TITLE
[docs] broken CSS on one of the docs pages

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#238]
As reported in https://github.com/datahq/datahub-qa/issues/169

## Acceptance criteria

* [x] http://datahub.io/docs/data-packages looks OK, e.g., info message in the bottom + edit on github button in the same place as on other docs pages

## Tasks

* [x] debug the page and find the source of the problem
* [x] implement the fix

**Comment by anuveyatsu** [comment]
FIXED https://testing.datahub.io/docs/data-packages
