### ISSUE TITLE
Front page and showcase page CSS improvements

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#239]
As reported in https://github.com/datahq/datahub-qa/issues/163

## Acceptance criteria

* [x] main action buttons appear correctly on smaller devices
* [x] footer doesn't overlap body's content, eg, buttons like on showcase page
* [x] BONUS: fix footer on smaller displays

## Tasks

* [x] implement html classes and CSS for action buttons and terminal element so they don't overlap
* [x] fix footer's position so it doesn't overlap body's content
* [x] fix footer's appearance so it looks good on smaller devices

**Comment by anuveyatsu** [comment]
FIXED and live in production.
