### ISSUE TITLE
Separate login and signup links

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#240]
As DataHub team, we want to increase the number of signups per day so that we have more people using our platform. 

Currently, we have the only link in the navbar `LOGIN` that goes to `/login` page. As we want to increase the number of signups, we are going to add a separate link in the navbar saying `Join for free`, which also goes to old `/login` page.

## Acceptance criteria

* [ ] I can see `Join for free` link in the navbar that stands out, e.g., has the orange colour.

## Tasks

* [ ] add a new link in the navbar on the right of login link
* [ ] bonus: add an encouraging message on the login page: "To be able to publish datasets you need to sign up:"

**Comment by zelima** [comment]
FIXED
