### ISSUE TITLE
Enable login with Google

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#241]
Put back Google - while Github is mainly used by coders, almost everyone has a google account.

## Acceptance criteria

* [x] I can login using my Google account

## Tasks

* [x] refactor route for `/login` and pass URL for login with google
* [x] refactor login page and put `Google` button
* [x] track logins with google

**Comment by zelima** [comment]
FIXED
