### ISSUE TITLE
Improve installation docs

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#242]
Installation docs should have separate sections for each OS and be more detailed (esp for windows) + should link to how to publish data docs.

## Acceptance criteria

* [ ] This docs http://datahub.io/docs/getting-started/installing-data have separate sections for MacOS, Windows and Linux
* [ ] It also should have an example of running `data help` command
* [ ] It also should have link to how to publish docs so users can continue reading
* [ ] It also should have a GIF showing how push process happens so users have some understanding already
* [ ] NPM installation comes before binaries

## Tasks

* [ ] Re-write instructions for each OS in the separate section and add more details where possible
* [ ] Add an example of running `data help` command
* [ ] Add a link to how to publish docs in the end
* [ ] Create a GIF of pushing process and put it in the end
* [ ] Put NPM installation before binaries as it's small enough and people who have NodeJS find it quickly
