### ISSUE TITLE
Add more info about CLI usage on Dashboard and Download pages

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#243]
As a part of epic to increase the number of people using the CLI app, we want to add more information about downloading and setting up on the Dashboard and Download pages.

## Acceptance criteria

* [x] on Dashboard page it suggests me to download the CLI app + links me to installation instructions
* [x] on Download page I can see a GIF of pushing a dataset using the CLI app

## Tasks

* [x] add a message about downloading the CLI app and a link to installation instructions on the Dashboard page
* [x] add a GIF of pushing a dataset on the Download page

**Comment by anuveyatsu** [comment]
@zelima can you review this issue by checking https://testing.datahub.io/dashboard and https://testing.datahub.io/download please

**Comment by anuveyatsu** [comment]
FIXED - http://datahub.io/download and also the dashboard page is now has more prominent notice about downloading and instructions:

<img width="1071" alt="screen shot 2018-03-28 at 16 29 16" src="https://user-images.githubusercontent.com/17809581/38023744-e90e7c0c-32a4-11e8-8991-823e60202df9.png">
