### ISSUE TITLE
[Docs] Improve Publishing data docs

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#244]
As a part of the epic to increase the number of people using the CLI app, we want to add sample data file for pushing + GIF of the process on http://datahub.io/docs/getting-started/publishing-data page.

## Acceptance criteria

* [x] I can get a sample file for getting started on publishing data docs page
* [x] I can see a GIF of how pushing happens

## Tasks

* [x] Create a sample data file (CSV)
  * [x] put it on Datahub
  * [x] and suggest to download it using `data get` and `/r/` link: `data get https://datahub.io/examples/sample-csv/r/0.csv` - https://github.com/datahq/datahub-qa/issues/179
* [x] put a GIF we've already created

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/docs/getting-started/publishing-data
