### ISSUE TITLE
Differentiate logins from website and CLI

### ISSUE THREAD

**Issue by zelima** [datahq/frontend#248]
As an admin, I want to know how people login so that I understand  why do people log in Datahub: cause CLI, cause showcase 404 or no reason.

## Acceptance Criteria

* [ ] We know who logged in via CLI
* [ ] We know who logged in via web 

## Tasks

* [ ] Analysis 
* [ ] refactor `/successs` route to `/successs?client={client}`
* [ ] refactor frontend `api.authenticate` method to redirect  on `/success?client=web`
* [ ] refactor login in CLI to redirect on `https://datahub.io/success?client=web`
* [ ] Set up GA event tracker for dashboard
* [x] update QA spreadsheet with new testcases

## Analysis

Current situation: For login, we use `datahub.io/success` endpoint as a redirect URL after successful login.

### Solution for WEB/CLI:

Instead of serving only `datahub.io/success` we can accept query parameter `/successs?client={client}`. In this case we can track the number of visits from GA

* CLI will hit `datahub.io/success?client=cli`
* Web will hit `datahub.io/success?client=web`

Since `success` route does nothing but redirects to `dashboard` we can not set GA tracker there. but w will set `req.session.client` to `web` or `cli` and pass it to the redirect (dashboard). 
`dashboard` route will grab client from `req.session` and we can set up GA event tracking feature there: https://developers.google.com/analytics/devguides/collection/analyticsjs/events

`ga('send', 'event', 'login', 'client')`
