### ISSUE TITLE
add SEO meta tags in order to improve sharing and discoverability

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#254]
We want to add SEO meta tags, so it improves sharing and discoverability.
Reported here https://github.com/datahq/datahub-qa/issues/183

## Acceptance criteria
* [x]  SEO meta tags has a dataset summary, social media information

## Tasks

* [x] add SEO meta tags for twitter
* [x] add SEO meta tags for dataset summary
* [x] add SEO meta tags for Open Graph

## Analysis

re twitter and og(Open Graph) tags, please read https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started

**Comment by anuveyatsu** [comment]
FIXED
