### ISSUE TITLE
[front page] implement datahub offers on front page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#257]
As part of "Marketing: datahub offers" epic, we want to do rework on front page of the website.

## Acceptance criteria

* [x] I can see following offers
  * [x] Publish and Deploy your Data
  * [x] Quality Data ready to Integrate
  * [x] DataOS
  * [x] Consulting
* [x] I can see 4 popular datasets

## Tasks

* [x] implement template for an offer
* [x] implement template for listing popular datasets
* [x] implement basic DataOS page
* [x] implement Consulting placeholder page
* [x] put on place all offers

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io
