### ISSUE TITLE
Consulting offer and page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#259]
## Acceptance criteria

* I can see a consulting offer on the front page [already done before]
* [ ] I can quickly contact DataHub re consulting/hiring
* [ ] I receive some sort of confirmation that my message was sent

## Tasks

* [ ] create an account on formspree using support email address
* [ ] create `consulting.html` template with all required fields
* [ ] setup formspree with the form on page
* [ ] test out
* [ ] improve layout and styles
* [ ] implement confirmation and thanking behaviour after submission
* [ ] add tests
