### ISSUE TITLE
Setup Google Analytics

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#26]
Check if GA is setup correctly, if not fix it.

## Acceptance criteria

* [x] on google analytics dashboard:
  * [x] I can see stats for the site
  * [x] I can see stats for file downloads

## Tasks

* [x] create new property under datopian account for datahub.io
* [x] update GA id in the `views/base.html`
* [x] verify it is working using GA dashboard

**Comment by anuveyatsu** [comment]
FIXED, `datahub.io` property added under `datopian` account on google analytics.

**Comment by rufuspollock** [comment]
@anuveyatsu how do you configure this? I don't see any docs in the README for this config variable.

**Comment by anuveyatsu** [comment]
@rufuspollock we do it in `base.html` in GA script in the bottom of template.
