### ISSUE TITLE
Implement experiments for Download page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#266]
## Acceptance criteria

* [x] experiments are setup and running for hypothesis on:
  * [x] /core/country-list
  * [x] /pricing
  * [x] /search
  * [x] /download

## Tasks

* [x] analyse the best way of impementing this, e.g., server-side vs UI provided by google optimize
* [x] implement experiments for:
  * [x] /core/country-list
  * [x] /pricing
  * [x] /search
  * [x] /download

## Analysis

Server-side solutions:

- https://stackoverflow.com/questions/48386350/google-tag-manager-optimize-server-side-experiment-sending-variation
- https://github.com/datahq/pm/issues/76

Problem with server-side rendering is that it requires additional coding work on the each experiment + it has number of uncertanties due to lack of documentation and discussion about how to implement it via Tagmanager. On the other hand, Optimize's UI provides enough tools to change and manipulate the page's layout + it is a standard way of implementing this. Thus, we've decided to go and use the UI way.

**Comment by anuveyatsu** [comment]
FIXED and 4 experiments are running now:

* core/country-list:

<img width="900" alt="screen shot 2018-05-10 at 12 59 52" src="https://user-images.githubusercontent.com/17809581/39856531-22c24b26-5452-11e8-8730-f3b7a335f078.png">

* pricing:

<img width="775" alt="screen shot 2018-05-10 at 12 59 27" src="https://user-images.githubusercontent.com/17809581/39856545-2d112f8e-5452-11e8-93fb-11a1ce3c3924.png">

* download:

<img width="1082" alt="screen shot 2018-05-10 at 12 58 47" src="https://user-images.githubusercontent.com/17809581/39856558-34509d70-5452-11e8-8662-c4dc143a8656.png">

* search:

<img width="1091" alt="screen shot 2018-05-10 at 12 57 18" src="https://user-images.githubusercontent.com/17809581/39856570-3ed3227c-5452-11e8-97b9-9173bdf1d781.png">
