### ISSUE TITLE
Design and review home page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#267]
# User Stories
* As a Visitor, i want to understand the product(s) quickly and easily so that I can then decide to try them out and use them (or not) 
* As a Visitor I want a visually appealing site so that I am engaged and look further
* As a Visitor I want to start using the products on offer quickly so that I can try them out and use them

# Acceptance Criteria 
* [x] Complete mock up of homepage 
* [x] Mockup must be elegant and should look modern and attractive
* [x] Mockup must have all the elements of datahub
* [x] Mockup must be engaging and explain about products and datahub with clarity
* [x] Mockup must be able so solve various UI/UX problems
* [x] Must provide at least 3 color combinations of home for comparison 

# Tasks
* [x] Do a UI/UX review of the website
* [x] Do a research on websites for fonts / color palette to create the best visual elements
* [x] Create a mockup of homepage
* [x] Go through revisions with anu
* [x] Present the final mockup to team and seek feedback

# Analysis
* Analysis was done based on list of popular websites including slack,stripe, npm, redash etc.  
* 3 wireframes for shaped up to get inputs of the team before getting to the mockups: 
https://app.moqups.com/tanvirchahal009/T28B4rsjL8/view/page/aa9df7b72

**Comment by tanvirchahal** [comment]
@anuveyatsu  shall i go ahead and mark the items done and close issue? 
Team has decided to go with V1

**Comment by anuveyatsu** [comment]
@tanvirchahal sure
