### ISSUE TITLE
Implement the new design for the home page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#268]
## Acceptance criteria

* [x] the home page is implemented as per mockups created by @tanvirchahal 
* [x] the page is reviewed and accepted by the team

## Tasks

* [x] analysis by @tanvirchahal and @anuveyatsu
* [x] implementation
  * [x] navbar
  * [x] hero element
  * [x] 3 offers section (under the hero)
  * [x] deploy data section
  * [x] quality data section
  * [x] dataos section
  * [x] hire us section
* [x] review
* [x] deployment

**Comment by anuveyatsu** [comment]
New homepage is available in staging site: https://testing.datahub.io

FIXED

cc @tanvirchahal
