### ISSUE TITLE
Define hypotheses for the home page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#269]
As we are implementing re-design of the home page, we are uncertain about what works best among different available options (e.g., which section should come first or where to put links in the navbar). Thus, we want to create a number of hypotheses that we can validate using experiments and google optimize.

## Acceptance criteria

* [x] at least 2 hypotheses created and reviewed by the team

## Tasks

* [x] analysis with possible A/B tests
* [x] write up hypotheses

## Analysis

This analysis assumes we already have implemented the new design of the homepage - https://projects.invisionapp.com/share/R6I4N6JDWM9#/screens/295499677

The idea of running A/B tests on the homepage is to understand which versions of different sections on the page works best, e.g., we can test call-to-action buttons by changing their order OR we can use different wording for some links in the navbar. Below, we're going to have a number of experiments that can be tested - the best way of testing all variants is to do a [multivariant test](https://support.google.com/optimize/answer/7012154#multivariate-tests)

Possible A/B tests we can implement for the homepage:

* wording in the navbar for current 'Download' page (note that we already dropped old 'Download' name):
  * 'Tools' vs 'CLI tool'
* login/signup buttons
  * 'Start publishing' vs 'Login/Signup'
* wording for the `/search` page in the navbar (we're not going to use 'collections' word):
  * 'Datasets' vs 'Find data'
* main call-to-action button variations
  * 'See products' vs 'What do we offer'
* main image
  * do we have any other alternatives? @tanvirchahal 

We will test different combinations of above, e.g., assuming that we have 2 variants of the main image, we would have `2*2*2*2*2 = 32` variants of the homepage from which we can select the best one.

### Hypotheses

* 'CLI tool' is more specific and as a link to `/download` page will increase number of clicks on it.
* Naming login button as 'Login/Signup' will increase number of clicks on it.
* 'Find data' is a better name for the search page and it'll increase number of clicks from the homepage on the link.
* 'What do we offer' is more descriptive wording for the main call-to-action button and it will increase number of clicks on it.

**Comment by akariv** [comment]
lgtm @anuveyatsu

**Comment by anuveyatsu** [comment]
FIXED
