### ISSUE TITLE
Create pricing page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#27]
We want to have `/pricing` page where all plans will be displayed. Design of the page: https://drive.google.com/a/datopian.com/file/d/0B7ucLyXmP0n2clZIOHdwRGJFaHc/view?usp=sharing

## Acceptance criteria

* [x] `/pricing` page indicates all necessary information about DataHub plans

## Tasks

* [x] create `/views/pricing.html` skeleton + link in navbar
* [x] create new route in `/routes/index.js` for `/pricing`
* [x] implement mockup design

**Comment by anuveyatsu** [comment]
FIXED in #29
