### ISSUE TITLE
Design and review the Consultancy page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#271]
Create a new design for Consultancy Page.  Design various sections showcasing our competency and our recent projects.

## Acceptance criteria
* [x]  new design has all the required sections
* [x] content and design is reviewed and accepted

## Tasks
* [x] Design the mockup
* [x] work on content with the team
* [x] make updates as per reviews and feedback
* [x] get the mockup approved

**Comment by anuveyatsu** [comment]
@tanvirchahal can you please update the description of this issue according to our standards. Once you've done it, please close the issue.
