### ISSUE TITLE
Design and review the DataOS page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#272]
Create DataOS mockup containing various sections for /data-os .  The mockup must include information about the process that dataOS uses

## Acceptance criteria
* [x] the dataOS design and content is approved
* [x] reviewed by the team

## Tasks

* [x] create content with adam
* [x] design the mockup
* [x] feedback and updates to content/design
* [x] finalize the mockup
