### ISSUE TITLE
Implement a new design for the Consultancy page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#273]
*Estimate is unknown until we have a mockup.*

## Acceptance criteria

* [x] the new design is implemented at `/hire-us`
* [x] reviewed by the team

## Tasks

* [x] analysis between @tanvirchahal and @anuveyatsu
* [x] implementation per the mockup
* [x] review
* [x] deployment
