### ISSUE TITLE
Implement a new design for the DataOS page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#274]
Implement the DataOS design with the mockups that are discussed and reviewed with the team.

## User Stories 
* As a user, I want a clean design for DataOS, so that I can easily understand what it offers and how it can be helpful for my project
* As a user, I want to clear path for DataOS, so that I can find dataos' features and how to use it
* As Project Owner, I want a new design on DataOS, so that it stands out to customers

## Acceptance criteria
* [x] the new design is implemented at `/data-os`
* [x] reviewed by the team

## Tasks
* [x] analysis between @tanvirchahal and @anuveyatsu
* [x] implementation per the mockup
* [x] review
* [x] deployment

**Comment by anuveyatsu** [comment]
FIXED see https://datahub.io/data-factory
