### ISSUE TITLE
Datahub Newsletter and Signup

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#275]
# User Story
* As a user, i need a subscribe form, so i can get monthly information about datahub
* As a user, i need monthly subscription, so i can stay updated about latest news/updates from datahub
* As an admin, i need users to subscribe for newsletter, so i can keep them engaged and connected to platform

# Acceptance Criteria
* [x] Have a fully functional subscribe input and button on datahub website
* [x] Users are able to subscribe to monthly newsletter from homepage and blog page
* [x] Monthly newsletter has a good interface and provides various sections that users can read
* [x] Monthly newsletter must a template that the campaign manager can edit each month to generate new content and send to subscribed users

# Tasks
* [x] Design a new template
* [x] Create various placeholders in the template and load static content in it
* [x] Create a subscribe form on datahub homepage
* [x] Create a subscribe form on datahub blogs page
* [x] Make sure the entries from subscribe form goes to monthly newsletter list

**Comment by anuveyatsu** [comment]
@tanvirchahal can you tick items as done and close this issue if fixed?
