### ISSUE TITLE
Share and embed links on full showcase pages not working

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#282]
As reported in https://github.com/datahq/datahub-qa/issues/226

## Acceptance criteria

* [x] I can copy share/embed links from full showcase page

## Tasks

* [x] identify the source of the bug in `showcase-js` repo + analysis
* [x] implement the fix in showcase-js
* [x] implement the route in the frontend
* [x] deploy

## Analysis

At the first sight, it looked like the problem is with incorrectly generated URLs, e.g., when you visit https://datahub.io/core/finance-vix/v/50, the share link would be https://datahub.io/core/finance-vix/v/50/view/0, however, we want users to be able to share views per specific revision. So the fix should take place in the frontend repo instead of showcase-js repo.

Another thing to consider is which URL would be more readable and clear, compare following 2 options:

- https://datahub.io/core/finance-vix/view/0?v=50 - in the params we also can have `?v=latest`
- https://datahub.io/core/finance-vix/v/50/view/0

The first option is definitely more readable and clear + it's easy to build a URL by hand when you need it. Therefore, we want to implement it.

**Comment by anuveyatsu** [comment]
FIXED - check https://datahub.io/core/finance-vix/v/50
