### ISSUE TITLE
Showcase page UX review [initial] + define hypotheses

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#283]
We want to do an initial UX review of the showcase page to be able to define hypotheses that we can test. It then will be used in the extended UX/UI review and redesign.

## Acceptance criteria

* [x] at least 2 hypotheses defined

## Tasks

* [x] UX review of the page
* [x] discussion between Tanvir, Anu and Adam (?)
* [x] define hypotheses
* [x] review and finilise

**Comment by anuveyatsu** [comment]
# Hypotheses

* Renaming "Download" button to "Download data files", "Data files" or "View dataset" will increase the number of clicks on the button (and as a subsequent number of downloads) as it is a more descriptive name.
* Placing description (short readme) section above dataset summary will decrease bounce rate as incoming users can understand what's the page about quickly.
* Placing "Import into your tool" section above "README" section will increase the number of users that interact with the page (clicking the tabs of tools).
* Placing "Data files" table above the graphs and having a short description underneath will increase the number of downloads.

The ultimate goal for all these hypotheses is to increase users' interaction with the showcase page. Therefore, we can set up A/B/n tests with the following objectives:

1. Increase number of downloads
2. Increase number of clicks such as "copy share/embed link"
3. Decrease bounce rate

@akariv please let me know your thoughts

**Comment by akariv** [comment]
@anuveyatsu this sounds good to me, let's go forward with this plan.

**Comment by anuveyatsu** [comment]
FIXED
