### ISSUE TITLE
Implement A/B tests for showcase page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#284]
Implement A/B tests for hypotheses defined in https://github.com/datahq/frontend/issues/283 

## Acceptance criteria

* [x] A/B tests are setup and working for hypotheses

## Tasks

* [x] draft experiments in google optimise
* [x] setup objectives
* [x] implement required changes to variants (eg, html, css implementation of a new version)
* [x] start experiments

**Comment by anuveyatsu** [comment]
FIXED - experiments started on 28 May 2018
