### ISSUE TITLE
Track successful Data Request submissions

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#285]
As Branko I want to be able to track successful Data Request form submissions so I can easily and quickly get number of requests per given perios, e.g., per sprint.

## Acceptance criteria

* [x] in the GA reports, we're tracking requests form submissions

## Tasks

* [x] add tracker for the submit button on requests page
* [x] verify it's being tracked via GA reports

**Comment by anuveyatsu** [comment]
FIXED, see `category: requests, action: data-request` in the GA events report.
