### ISSUE TITLE
Cannot access resources and descriptor per specific revision

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#286]
As a User, I want to be able to go to the specific revision of my dataset and download resources/descriptor at that stage so I can control/access my files history.

Currently, if you go to full URL, e.g., https://datahub.io/core/finance-vix/v/50 and try to access a resource or descriptor, it'd give you the latest version.

## Acceptance criteria

* [x] I can go to https://datahub.io/core/finance-vix/v/50 and download the resources at this stage

## Tasks

* [x] refactor routes for `/datapackage.json` and `/r/` so it considers `v` option in the params
* [x] refactor showcase.html template to include revisionId in the params where required

**Comment by anuveyatsu** [comment]
FIXED - check https://datahub.io/core/finance-vix/v/50
