### ISSUE TITLE
Create logo for awesome pages

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#291]
Create a b/w logo for each of the awesome pages matching the overall look and UI of the website

## User Stories
* As a User, I want to see logo per each awesome page theme/category so I have better UX while browsing the website.
* As a Developer, I want to have a logo per each awesome page so I can use it as "meta image" tag that is then used in search results/sharing on social media.

## Acceptance criteria
* [x] There is a logo for each category of awesome page

## Tasks
* [x] create a list of categories that need a logo
* [x] analysis and mockup
* [x] review

**Comment by zuuritaly** [comment]
Hello @anuveyatsu 
I'm a graphic designer and I design logos for open source projects.
Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by anuveyatsu** [comment]
Hi @zuuritaly 
This sounds awesome 👏 your help here would be appreciated!

At DataHub, we have the "Awesome collections" of datasets, where we categorize data by subject. For example, we have "Economic data and indicators". You can overview existing "Awesome collections" here - https://datahub.io/awesome

What we want is to create a logo (image) for them so they represent the subject.

For example, we already have an image for "CO2-PPM" dataset:

<img width="259" alt="screen shot 2018-06-25 at 01 26 08" src="https://user-images.githubusercontent.com/17809581/41822788-0b6d54d2-7817-11e8-8776-543ceeec049b.png">

Re your questions:
* we want all images to be aligned in style (e.g., you can consider "CO2-PPM" image)
* we don't have anything specific so open to experiment
* colours are black, white and gray

Thank you!

**Comment by zuuritaly** [comment]
Hi, Just a question, the project name is datahub? right?

**Comment by anuveyatsu** [comment]
@zuuritaly yes, the project name is datahub

**Comment by anuveyatsu** [comment]
Hi @zuuritaly thanks again for willingness to help us in this item. Would you have time this week to have a quick chat so we can get clear about the details? Also, do you have any approx timelines about this task?

Thanks!

**Comment by zuuritaly** [comment]
Hi @anuveyatsu 
I create this design for the Datahub, I used a cloud like the CO2 image that you show and add lines and dots as a reference to data.

Best Regards
Zuur

![datahub proposal](https://user-images.githubusercontent.com/40405175/42159169-b64b2eb4-7dea-11e8-9632-eb33ff768ca0.png)

**Comment by anuveyatsu** [comment]
Hey @zuuritaly 

This is a nice job! However, you have probably misunderstood me about what we need here. Let me explain it in a better way:

We already have a logo for our project DataHub. Now we need a logo (or let's call it icons so we don't get confused) for each awesome collections section. For example, we have "Economic Data & Indicators" collection and we need an icon for it. It can be something representing "economy" theme. We could start with this 1 icon and then go with other themes. What do you think?

Do you want to have a chat so we're on the same page?

Thanks!

**Comment by anuveyatsu** [comment]
Closing this issue as FIXED - we have icons in our google drive.
