### ISSUE TITLE
A new design for the awesome pages

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#292]
Create a new design for awesome pages
https://datahub.io/awesome

## User Stories 
* As the DataHub team, we want to have more interactive layout of the awesome pages, so that users arriving there have great UX.
* As user, I want a clear design for the awesome page, so that  I can clearly understand various types of data offered by Datahub 

## Acceptance criteria
* [x] we have a reviewed mockup of the page

## Tasks
* [x] brainstorm and consult with the team about the new look
* [x] create a first version of the mockup and pass it to review
* [x] update mockup as per review

**Comment by zelima** [comment]
FIXED. We now have nice looking awesome pages (renamed to collections) https://datahub.io/collections
![image](https://user-images.githubusercontent.com/15143785/46531482-72c24880-c8ae-11e8-8ddd-f85830de05f3.png)
