### ISSUE TITLE
Implement the new design for the awesome pages

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#293]
Using the mockup created in #292 implement the HTML/CSS and deploy.

## User Stories 
* As the DataHub team, we want to have more interactive layout of the awesome pages so users arriving there have great UX.
* As user, I want a clear design for the awesome page,so that  I can clearly understand various types of data offered by Datahub 

## Acceptance criteria

* [x] new design is live at `/awesome`

## Tasks

* [x] implement the new design in `/views/awesome.html` and `/public/sass/_awesome.scss`
* [x] get reviewed
* [x] fix requested changes
* [x] deploy

**Comment by zelima** [comment]
FIXED. move to collections https://datahub.io/collections
