### ISSUE TITLE
Showcase page interactions

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#295]
As the DataHub team, we want to improve showcase page interactions so we know that incoming users are finding what they've been looking for.

## Acceptance criteria

* [x] a/b tests for the premium data banner is running
* [x] a/b tests for different messages for automation/fetching is running
* [x] related datasets section exists on `country-list` page
* [x] message on 'import your data' about data-cli is improved

## Tasks

* [x] play around with the banner about premium data
* [x] related datasets: on country-list have a related datasets (we can have as "related" property in dp.json)
* [x] Improve message on 'import your data' about data-cli (needs some fixes to English, for example)
* [x] New experiments 
    * [x] Try different messages for automation/fetching experiment
    * ~~Consider changing download links ('csv', 'json') to buttons~~ doesn't look good inside the table

### Play around with the banner about premium data

Current language:

> We're introducing a premium data service that includes notifications, data customization and more.
> Sign up for our free trial program to find out more and tell us what you'd most want to see first!

We want to make it short, clear and direct so users click on "find out more". Our assumtion is that most users want customization, e.g., like Fedex does.

We can try these experiments on `s-and-p-500-companies` dataset page:

#### Variant 1

Customize this data set with our "Premium Data" service - [find out more](link).

#### Variant 2

Build on top of this data set with automated updates, notifications and more - [sign up now!](link)

#### Variant 3

Integrate this data set into your workflow - [learn more](link).

#### Actions

* [x] Using 3 variants above, create A/B tests on `s-and-p-500-companies` dataset page

### Improve message on 'import your data' about data-cli

Current message is weak and wrong English: "Import into your tool"

We can rename it to: "Integrate into your favourite tool"

Also description message about "data-cli" also can be improved:

> Data-cli or just data is the program to get and post your data with the datahub.
> Download CLI tool and use it with the datahub almost like you use git with the github

to something like:

> Use our [data-cli](https://datahub.io/download) tool designed for data wranglers

### Try different messages for automation/fetching experiment

Use following showcase page for these experiments: https://datahub.io/core/country-list

Originally, there is no button/info on the top of the page. We had experiments before but it didn't provide us any specific results.

#### Variants

1. `Integrate` - as integrate into your tool or use it from your favourite tool
2. `Developers` - as instructions for developers. In fact, those instructions are advanced (not for non-tech users)
3. `API` - as general description of what it is

#### Actions

* [x] create a A/B tests using above 3 variants on https://datahub.io/core/country-list

**Comment by anuveyatsu** [comment]
FIXED, A/B tests are scheduled to start on June 22 at 2pm GMT
