### ISSUE TITLE
Re-setup A/B tests for showcase page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#296]
The previous implementation of A/B/n tests in showcase page caused bugs:

* it was loading country-list dataset initially and then showing appropriate dataset
* field information table was taken from country-list dataset for all other core datasets
* showcase page was not loading smoothly - it was jumpy and content was changing during the page load

This was because we wanted to apply A/B/n tests for all core dataset pages. We should instead run experiments on one page. Therefore, we will test each hypothesis on a separate page, e.g., "short readme is above dataset summary" will be tested on "s-and-p-500" dataset.

## Acceptance criteria

* [x] Experiments are running properly

## Tasks

* [x] draft an experiment for each hypothesis on separate page
* [x] setup objectives, create rules
* [x] start experiments

**Comment by anuveyatsu** [comment]
FIXED. A/B tests started on 2 June 2018.
