### ISSUE TITLE
[Home] Re-organize sequence of sections and add more prominent links

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#297]
As the DataHub team, we want our homepage to be structured and logical so when search engines like google crawl the page it can easily understand which pages are the most important (and what links).

## Acceptance criteria

* [x] Core data section comes first and before Publish data section
* [x] Each section has a link in the heading to the relevant page, e.g., Core data section's heading links to `/core`

## Tasks

* [x] restructure sections so:
  * core data comes first
  * request data comes second
  * publish data comes third
* [x] in core data section, add a link in the heading to `/core`

**Comment by anuveyatsu** [comment]
FIXED see new homepage
