### ISSUE TITLE
[Publisher] Improve title and meta description for publisher page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#298]
As the DataHub team, we want to have a descriptive title and description for the publisher page especially for 'core' and 'machine-learning' publishers so it has better ranking in search engines and SEO in general.

## Acceptance criteria

* [x] title and meta description for 'core' and 'machine-learning' users have clear text using SEO oriented wordings

## Tasks

* [x] refactor routes to define title and description properties:
  * [x] have special title and description for special users

**Comment by anuveyatsu** [comment]
FIXED
