### ISSUE TITLE
[Showcase] Rows are sorted in a wrong way in some cases

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#299]
@zelima commented on [Fri Jun 01 2018](https://github.com/datahq/assembler/issues/100)

While original data is sorted Eg by dates, sometimes we have cases when processed data is resorted in a strange way, to be exact one of the 2 rows are swapped. For example, take a look at this dataset https://datahub.io/datahq/datahub-kpis and one of it's graphs https://datahub.io/datahq/datahub-kpis/view/7

## Acceptance Criteria

* [x] We know the reason behind this
* [x] Bug is eliminated (if related to us)

## Tasks

* [x] investigate reason
* [ ] create test case if possible 
* [x] Fix

## Analysis 

Looking at the data prepared for rendering it does not seem to be the backend problem as it is sorted normally. Eg: Looking at this dataset https://datahub.io/datahq/datahub-kpis/v/76

* Both graph and table have `2018-05-24` before `2018-05-24`
  * ![image](https://user-images.githubusercontent.com/15143785/41344160-7dd87740-6f11-11e8-842b-6da2a71d2cf9.png)
  * ![image](https://user-images.githubusercontent.com/15143785/41344272-b6c5c12a-6f11-11e8-85ad-53249ff49e4f.png)

* Both are using the data from the resource called `premium-data-funnel-weekly`
* `premium-data-funnel-weekly` itself is sorted normally 
  * direct link https://pkgstore.datahub.io/datahq/datahub-kpis/premium-data-funnel-weekly/archive/8cac6fd79a148525b1c876809a9a4485/premium-data-funnel-weekly.csv
 * "R" link: https://datahub.io/datahq/datahub-kpis/r/premium-data-funnel-weekly.csv?v=76

As a conlusion think this is not the backend problem, but maybe the bug of a parsing library Eg tranformin CSV --> list in frontend

---

@anuveyatsu commented on [Wed Jun 13 2018](https://github.com/datahq/assembler/issues/100#issuecomment-396885950)

@zelima OK, I agree it must be a problem in the frontend. I will move this issue to the 'frontend' repo.

**Comment by anuveyatsu** [comment]
FIXED: this was an old bug with tableschema library which was fixed in v1.7.0
