### ISSUE TITLE
Track pageviews on the server-side as events

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#300]
As the DataHub team, we want to double check how many page views are we having so we know the total number of our users including those who use Adblockers (it blocks google analytics and tag manager snippets).

We can use NPM package for google analytics here.

https://medium.freecodecamp.org/save-your-analytics-from-content-blockers-7ee08c6ec7ee

## Acceptance criteria

* [x] I can see special events that contain number of page views in the GA dashboard

## Tasks

* [x] install analytics npm package
* [x] identify where implementation should take place
* [x] implement
* [x] deploy

**Comment by anuveyatsu** [comment]
FIXED and being tracked
