### ISSUE TITLE
[SEO] Structured data & rich results

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#301]
What's Structured Data: metadata about the page that Google understands
What's Rich Cards (renamed now as Rich Results): Rich results are search results that go beyond the standard blue link

## Acceptance criteria

* [x] search results for datahub looks prominent

## Tasks

* [x] analysis, create list of features we can implement
* [x] implementation
  * [x] sitelink searchbox
  * [x] breadcrumb
  * [x] logo
  * [x] social profile
  * [x] carousel
  * [x] content types: ~~dataset~~ article
* [x] deployment

### Features that can be used for DataHub

* Enhancements
  1. Sitelinks Search Box - https://moz.com/blog/sitelinks-search-box
  2. Breadcrumb - https://moz.com/blog/using-google-tag-manager-to-dynamically-generate-schema-org-json-ld-tags
  3. Logo
  4. Social profile
  5. Carousel (eg, datasets by subject such as economic data: gdp, cpi etc are rendered as a carousel)
* Content Types: Dataset - https://developers.google.com/search/docs/data-types/dataset

**Comment by anuveyatsu** [comment]
FIXED but we will need to verify if google search is rendering rich results for the site (probably in 1-2w time when all pages are re-indexed)
