### ISSUE TITLE
Brainstorm About Premium Data Offer

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#304]
Brainstorm about premium data offer, eg, how we can increase attention and engaging users - have ~20 different ideas of how we can improve it and pick 3-4 @tanvir @anu

## User Stories
* As Project Owner, I want to promote premium data offer, so that I can drive more leads regarding the same.
* As Tanvir, I want to enhance premium data offer UI, so that it appeals more the prospective clients and users
* As User, I want to premium data offer on the website, so that I can find it on the website to request data that I need

## Acceptance Criteria
* [x] Approximately 20 ideas consolidated in a document
* [x] Ideas discussed
* [x] 3-4 Ideas selected for the improvement of premium data offer

## Tasks
* [x] Work with Anu to brianstorm ideas
* [x] Document the ideas
* [x] Review together Anu + Tanvir
* [ ] Review the ideas with team
* [x] Select 3-4 ideas for further work 

## Analysis

Current situation:

We have a banner on top of each "core" datasets pages, which doesn't seem to be prominent.

### Ideas

* a message around preview tables because it is where users see the data
* banner doesn't look like an offer
* we could have orange (bright) borders for the banner
* we could have a button next to resource title, eg, instead of download button
    * we also could have similar button next to "Field Information" heading
* message about premium data offer just above "This is a preview version." sentance
* Writing the offer in a ribbon that scrolls with user - increases chances of visibility
* Make the offer ribbon stick to the bottom of the page 
https://www.commonsensemedia.org/reviews/category/website/genre/gaming-20247
* Better verbiage with a clear call to action, current version is so ambigious and long.  Possible Version "**If none of this datasets suit you, get help from our experts -- Get in Touch**"
* Better design for the ribbions / message elements, cleaner ui always works 
https://trello.com/c/LPUgjVT3/2-ribbon-ui-inspiration
Another example of stick ribbon: https://www.cherryservers.com/?gclid=Cj0KCQjwvezZBRDkARIsADKQyPlu7RfLXRCMEmyXMZtdG7tgaxGjmrIZFeAEAzFBA-plaMfO9TaqTEMaAnQsEALw_wcB
* Popups to inspire customers about Premium Data after say 10s of the load
https://nobhvr.com/?gclid=Cj0KCQjwvezZBRDkARIsADKQyPl3gjqJf_fhvB_1wlznD8MwILlFN0lglRmd8pBTKHSJfWWMhtIE-YgaAl-gEALw_wcB
* Sticky "Cant Find What you're looking for" button on top right corner -  Click opens the signup popup
Example (Check Top Right Corner):
https://officialtagclothing.co.uk/collections/stance-collection
* Dedicated Preimum Data offer section at the bottom of each page.
Example: 
https://trello.com/c/kEHBOZBa/3-dedicated-section
Personal Favourite: https://trello-attachments.s3.amazonaws.com/5b3baaab4b0e6eee5e391c24/5b3bad1cd3819a74d7531094/36887c5c8edca29c99663bdcb4305b88/fe954392decd82df40e92eb407e965d4.jpg
* Improve modal design, the current version looks not so professional
Example: https://trello.com/c/Rps8MdfN/4-modals
* Sticky Button on the side for "Find More Data" or something. 
Example (checkout the scrolling example button and click behaviour): https://www.alibabacloud.com/product/ecs?tab=enterprise&utm_content=se_1427384&gclid=Cj0KCQjwvezZBRDkARIsADKQyPmGQNgO3jnrLEsejQTWMwGc7Q63D5O30mPrAAXWmVyf9Sh7pDY_ChAaAvydEALw_wcB
* Create in page sections that are sort of advertisements for reminding customers that they can always reach us if they can't find right data
Example (check out the green 'Stay up to date on new reviews' section) : https://www.commonsensemedia.org/website-reviews/sploder
* Small messages with an info logo under datasets saying "We can help finding you the right data"
Example : https://trello-attachments.s3.amazonaws.com/5b3baaab4b0e6eee5e391c24/5b3bac104d92988f2fa070e8/3a061666fde486ea474786cf92c93af6/image.png
* Change the inputs of the preimum data offer, or maybe change it to chat if possible

### Likes

* a message around preview tables because it is where users see the data
    * https://trello-attachments.s3.amazonaws.com/5b3baaab4b0e6eee5e391c24/5b3bac104d92988f2fa070e8/3a061666fde486ea474786cf92c93af6/image.png
* Make the offer ribbon stick to the bottom of the page 
https://www.commonsensemedia.org/reviews/category/website/genre/gaming-20247
* Better verbiage with a clear call to action, current version is so ambigious and long.  Possible Version "**If none of this datasets suit you, get help from our experts -- Get in Touch**"
* Better design for the ribbions / message elements, cleaner ui always works https://www.cherryservers.com/?gclid=Cj0KCQjwvezZBRDkARIsADKQyPlu7RfLXRCMEmyXMZtdG7tgaxGjmrIZFeAEAzFBA-plaMfO9TaqTEMaAnQsEALw_wcB
* Dedicated Preimum Data offer section at the bottom of each page. https://trello-attachments.s3.amazonaws.com/5b3baaab4b0e6eee5e391c24/5b3bad1cd3819a74d7531094/36887c5c8edca29c99663bdcb4305b88/fe954392decd82df40e92eb407e965d4.jpg
* Improve modal design and content, the current version looks not so professional
Example: https://trello.com/c/Rps8MdfN/4-modals
    * Change the inputs of the preimum data offer, or maybe change it to chat if possible
