### ISSUE TITLE
Mockups for effective showcasing of Premium Data Offer

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#305]
Create mockups of selected 3-4 ideas to improve findability of premium data offer @tanvir

## User Stories
* As Project Owner, I want to promote premium data offer, so that I can drive more leads regarding the same.
* As Tanvir, I want to enhance premium data offer UI, so that it appeals more the prospective clients and users
* As User, I want to premium data offer on the website, so that I can find it on the website to request data that I need

## Acceptance Criteria 
* [x] Mockups are based on 3-4 ideas chosen in #304 
* [x] Mockups Reviewed by team and satisfactory

## Tasks
* [x] Grab the team approved ideas from #304 
* [x] Create Mockups
* [x] Get them reviewed with team
* [ ] Update based on feedback
* [x] finalize

**Comment by tanvirchahal** [comment]
Links to Mockups
## Premium Data Offer Ribbon Section (Sticky Bottom)
* https://invis.io/MXMN8A6U4BQ
* https://invis.io/W9MN8APKVYN

## Premium Data Offer Promotional Section
* https://invis.io/HDMN8CFBRZS
* https://invis.io/36MN8DVB5FK

## Offer Popup/Modal 
* https://invis.io/K7MN8EEAS2E

## Table Information
* https://invis.io/B4MN8HYFMPA

**Comment by anuveyatsu** [comment]
FIXED - mockups was discussed and selected between @tanvirchahal and @anuveyatsu
