### ISSUE TITLE
Implement Premium Data Offer Ideas

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#306]
Implement the 3-4 ideas that are formulated in #304  and approved in #305 

## User Stories 
* As Project Owner, I want to Premium Data Offer reorganized, so that more users can discover it and signup for Premium Data Offer
* As User, I want Premium Data Offer more visible,  so that I can find an easy way to find premium data on datahub
* As Developer, I want to update Premium Data Offer, so that it can drive more users than before
* As Developer, I want to update Premium Data Offer, so that I can run a/b tests to conclude what works and what doesn't

## Acceptance Criteria 
* [x] Implemented based on #304 and #305 analysis and design
* [x] Reviewed by the team 
* [x] Pushed to website for testing and experiments 

## Tasks
* [x] Code the changes based on previous analysis and design
* [x] Get it reviewed by the team
* [x] Changes based on the review
* [x] Implement

**Comment by anuveyatsu** [comment]
FIXED and should be live
