### ISSUE TITLE
Conduct A/B Test on Premium Data Offers

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#307]
As the DataHub team, we want to conduct A/B tests with 3-4 versions of 'premium data' data on the showcase page so that we can identify which version works best.

## Acceptance Criteria

* [ ] experiments are setup and running

## Tasks

* [ ] create objectives of the experiments
* [ ] draft the A/B test
* [ ] setup
* [ ] implement changes for each version
* [ ] run/schedule the start

**Comment by anuveyatsu** [comment]
WONTFIX - no need to conduct a/b tests at the moment.
