### ISSUE TITLE
[Showcase] Analysis of DataTables vs Handsontable

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#308]
As the Datahub team, we want to see if DataTables is a better library in terms of our needs so that we can decide to use it and improve our website.

## Acceptance criteria

* [ ] report about the comparison of two libraries. Should include impact on bundle size, layout improvements, ease of use and functionality

## Tasks

* [ ] install DataTables and build a bundle
* [ ] analyse new bundle size
* [ ] analyse new layout and possible functionality
* [ ] create a report

**Comment by anuveyatsu** [comment]
Closing this issue as WONTFIX as using DataTables library in the React project creates complications, eg, it doesn't work without jquery, which is not the best fit with React. Another disadvantage of DataTables that they're docs lacks of examples with code examples, while Handsontable has more detailed docs. As per bundle size, DataTables could decrease bundle size by ~200kb which is not a big deal in our case.
