### ISSUE TITLE
Rename "DataOS" => "Data Factory"

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#309]
As the Datahub, we want to rename our "DataOS" product to "Data Factory" so that it is unique, more descriptive for the users.

## Acceptance criteria

* [x] "DataOS" is renamed in the homepage and in the product page itself
* [x] `/data-os` page doesn't exist but `/data-factory` is now available instead

## Tasks

* [x] Update the routes
* [x] Update verbiage on hompe, data factory page and the links
* [x] Updates to classes
* [x] Deploy and review
