### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#31]
We want to have redesigned dashboard page that would have all essential information and nice layout (we can have a look at zeit.co dashboard page).

* The page's title: `Your Dashboard`.
* Main account info: user's email address with gravatar.
* Indicate user's current plan
* Display how many packages user owns
* (?) We may also have last activities section.

## Acceptance criteria

* [x] Easily readable and minimal design
* [x] All pointed information above is on the page (except one with question mark)

## Tasks

* [x] refactor routes to pass necessary data
* [x] create new function in utils for getting currentUser's info
* [x] tests
* [x] refactore (redo) dashboard page's template
* [x] work on styles

**Comment by anuveyatsu** [comment]
FIXED in #32
