### ISSUE TITLE
[views] Puppeteer page crashes occasionally

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#314]
Error log 1:

```
(node:26) UnhandledPromiseRejectionWarning: Error: Page crashed!
    at Page._onTargetCrashed (/frontend-app/node_modules/puppeteer/lib/Page.js:156:24)
    at CDPSession.Page.client.on.event (/frontend-app/node_modules/puppeteer/lib/Page.js:132:56)
    at emitOne (events.js:116:13)
    at CDPSession.emit (events.js:211:7)
    at CDPSession._onMessage (/frontend-app/node_modules/puppeteer/lib/Connection.js:232:12)
    at Connection._onMessage (/frontend-app/node_modules/puppeteer/lib/Connection.js:119:19)
    at emitOne (events.js:116:13)
    at WebSocket.emit (events.js:211:7)
    at Receiver.receiverOnMessage (/frontend-app/node_modules/ws/lib/websocket.js:720:20)
    at emitOne (events.js:116:13)
```

Error log 2:

```
{ Error: Protocol error (Emulation.setDeviceMetricsOverride): Target closed.
    at Promise (/frontend-app/node_modules/puppeteer/lib/Connection.js:202:56)
    at new Promise (<anonymous>)
    at CDPSession.send (/frontend-app/node_modules/puppeteer/lib/Connection.js:201:12)
    at EmulationManager.emulateViewport (/frontend-app/node_modules/puppeteer/lib/EmulationManager.js:40:20)
    at Page.setViewport (/frontend-app/node_modules/puppeteer/lib/Page.js:701:54)
    at Page._screenshotTask (/frontend-app/node_modules/puppeteer/lib/Page.js:812:18)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Error log 3:

```
Error: waiting for selector "svg" failed: timeout 30000ms exceeded
    at Timeout.WaitTask._timeoutTimer.setTimeout (/frontend-app/node_modules/puppeteer/lib/FrameManager.js:841:60)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
```

Error log 4:

```
Error: Navigation Timeout Exceeded: 30000ms exceeded
    at Promise.then (/frontend-app/node_modules/puppeteer/lib/NavigatorWatcher.js:73:21)
    at <anonymous>
```

## Acceptance criteria

* [ ] page doesn't crash and the exception is handled

## Tasks

* [x] analyse error source 
* [x] handle page errors
* [x] improve logs

https://github.com/GoogleChrome/puppeteer/issues/1401
https://github.com/GoogleChrome/puppeteer/issues/1385

**Comment by anuveyatsu** [comment]
FIXED
