### ISSUE TITLE
Error visiting showcase page on Windows

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#316]
Sun, 08 Jul 2018 15:27:55 GMT express-session deprecated undefined resave option; provide resave option at index.js:32:11
Sun, 08 Jul 2018 15:27:55 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at index.js:32:11
Listening on :4000
(node:12232) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): FetchError: invalid json response body at https://api.datahub.io/resolver/resolve?path=core\population-growth-estimates-and-projections reason: Unexpected token l in JSON at position 0
(node:12232) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Acceptance criteria

* [x] showcase page loads OK locally on Windows

## Tasks

* [x] identify the source
* [x] implement the fix

**Comment by anuveyatsu** [comment]
FIXED
