### ISSUE TITLE
[Pricing] Improvements on pricing page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#319]
As the DataHub team, we want to have more up-to-date information about our offers on pricing page so that visitors know what exactly we're offering and can get in touch if interested.

## Acceptance criteria

* [x] all offers are defined on the pricing page

## Tasks

* [x] add premium data offer
* [x] add consulting link from there
* [x] add enterprise offer (we host for you or you run on premise)

**Comment by anuveyatsu** [comment]
FIXED - https://datahub.io/pricing
