### ISSUE TITLE
Homepage improvements per GA analysis

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#320]
Update the homepage to improve the visits on /core /requests and /downloads based on https://github.com/datahq/pm/issues/193

Should move the offer sections above the fold
Reduce the number of unnecessary links
add a link to /download page in the 'Publish' section of the homepage
add a prominent button/link to /download that says, eg, Get our data wrangler tool

## User Stories
* As a user, I want clear call to action buttons, so that its easier for me to navigate to main products.
* As a user, I want less links, so that its easier for me to explore the datahub without getting confused
* As datahub dev, I want to put clear offers, so that there is an increase in the page visits on offer pages

## Acceptance Criteria
* [x] Mockups and designs approved
* [x] Homepage changes updated

## Tasks
* [x] Create mockups
* [x] Implement Updates
* [x] Review and Feedback
* [x] Finalize updates

**Comment by anuveyatsu** [comment]
FIXED and live in production - https://datahub.io/
