### ISSUE TITLE
Create mockups for climate change dashboard design

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#321]
Create mockups for climate change dashboard design
https://testing.datahub.io/awesome/dashboards/climate-change

## User Stories
* As a user, i want a clean user interface for dashboard, so that its easier for me to surf the website
* As a user, I want a clean design, so that I can focus on the data reports
* As datahub dev, I want a clean design, to attract more users

## Acceptance Criteria
* [x] Mockups are visually attractive
* [x] Mockups are modern and align to datahub modern design
* [x] Mockups are reviewed and accepted

## Tasks
* [x] Brainstorm ideas
* [x] Create Mockups
* [x] Review and Feedback
* [x] Final Updates

**Comment by tanvirchahal** [comment]
@anuveyatsu 
https://invis.io/6KN4AUPZNP9
https://invis.io/PMN4AVKY485

**Comment by anuveyatsu** [comment]
@tanvirchahal great stuff! Let's implement https://invis.io/6KN4AUPZNP9 but:
* we don't need summary information in the bottom of the graphs
* notice that graphs are iframes so you'll need to play around with the dimensions
* you cannot hide/modify titles that are coming from iframes
