### ISSUE TITLE
Implement design for climate change dashboard

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#322]
Implement design for climate change dashboard based on #321 

## User Stories
* As a user, I want a clean user interface for the dashboard so that its easier for me to surf the website
* As a user, I want a clean design, so that I can focus on the data reports
* As datahub dev, I want a clean design, to attract more users

## Acceptance Criteria
* [x] Design presented in mockup is implemented
* [x] Design is reviewed by team and is free of bugs
* [x] Desing is tested on various devices and screens

## Tasks
* [x] Develop the interface based on mockups
* [x] Review and Feedback
* [x] Make updates
* [x] Test on various screens and devices

**Comment by anuveyatsu** [comment]
FIXED, see https://testing.datahub.io/awesome/dashboards/climate-change
