### ISSUE TITLE
Brainstorm about 'Similar Datasets' section

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#323]
Brainstorm about 'Similar Datasets' section, eg, see https://datahub.io/core/country-list

## User Stories
* As a user, I want similar datasets, so that I can find similar items related to my search
* As a developer, I want similar datasets, so that I can keep the users engaged
* As a developer, I want similar datasets, so that I can help users educate more about the kind of datasets datahub offers

## Acceptance Criteria
* [x] Ideas are brainstormed and laid down in a document
* [x] Moodboard is presented to find best practices across the web
* [x] 3-4 Ideas are selected

## Tasks
* [x] Brainstorm ideas
* [x] Create moodboard on trello
* [x] Discuss with anu and select 3-4 ideas

**Comment by anuveyatsu** [comment]
FIXED - ideas are selected for further implementation
