### ISSUE TITLE
Mockups for 'Similar Datasets' section

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#324]
Create mockups for similar datasets based on #323 

## User Stories
* As a user, I want similar datasets, so that I can find similar items related to my search
* As a developer, I want similar datasets, so that I can keep the users engaged
* As a developer, I want similar datasets, so that I can help users educate more about the kind of datasets datahub offers

## Acceptance Criteria
* [x] Mockups are created
* [x] Mockups are aligned with ideas selected from moodboard
* [x] Mockups aligning with new datahub design

## Tasks
* [x] Create mockups with variations
* [x] Feedback and review
* [x] Finalize design to be implemented

**Comment by tanvirchahal** [comment]
@anuveyatsu we have 4 alternatives to choose from
https://invis.io/2ZN2VZGE4GY
https://invis.io/HBN2VZOR4KW
https://invis.io/RTN2VZV27EC
https://invis.io/A7N2W00DSBV
