### ISSUE TITLE
Implementation of 'Similar Datasets' section

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#325]
Implementation of 'Similar Datasets' section based on #324 

## User Stories
* As a user, I want similar datasets, so that I can find similar items related to my search
* As a developer, I want similar datasets, so that I can keep the users engaged
* As a developer, I want similar datasets, so that I can help users educate more about the kind of datasets datahub offers

## Acceptance Criteria
* [x] New design is implemented based on mockups
* [x] Similar datasets are tested, should be functional and eye-catching

## Tasks
* [x] Develop based on mockups
* [x] Feedback and Review
* [x] Updates based on feedback
* [x] Finalize
