### ISSUE TITLE
Need to know from which showcase page 'premium data' request was submitted 

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#329]
As the DataHub team, we want to know from which page 'premium data' submission was sent so that we have a better understanding about the user's request.

## Acceptance criteria

* [x] when I receive a premium data signup request, I know from which showcase page it was sent

## Tasks

* [x] analyse the problem and identify where it should be fixed
* [x] figure out how to access parent window  location since our submission form is in the iframe
* [x] implement the fix

**Comment by anuveyatsu** [comment]
FIXED and tested
