### ISSUE TITLE
Feedback on UI (from meeting with Sylvie on 11 JULY 2017)

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#33]
## Tasks

* [ ] center packages in front page
* [x] rename Huber => Basic
* [x] find sharper icon for download button (fontawesome)
* [x] move API link in the footer to header + fix the link which is not working atm
* [x] handsontable values alignment - https://github.com/frictionlessdata/datapackage-render-js/issues/39

**Comment by rufuspollock** [comment]
FIXED. This was basically done. Centering packages can be done asap.

**Comment by anuveyatsu** [comment]
Centering packages are done as well.
