### ISSUE TITLE
User Dashboard - Brainstorming session

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#332]
User dashboard that is at `/dashboard` - we should make it for people who want to get data but right now it's only for who want to publish.

Brainstorming session - come up with 2-3 possible solutions/design/layout

## User Stories
* As a user, I want more clarity on the dashboard, so that I can find what I want from the dashboard
* As a user, I want the get data features on the dashboard, so that I can use it not just for publishing purposes
* As a user, I want a cleaner UI on the dashboard, that it helps me find what I want with minimal efforts.

## Acceptance Criteria
* [x] 10-15 ideas laid down
* [x] Ideas discussed with a reviewer
* [x] Relevant ideas are selected for implementation

## Tasks
* [x] Prepare moodboard
* [x] Prepare a list of ideas
* [x] Discuss ideas with team members
* [x] Select ideas to be implemented

**Comment by tanvirchahal** [comment]
# Actions
What we want to have in the dashboard (/dashboard):

* we want to focus on people who wants to find data (not publish)
* publisher specific info is still there but somewhere underneath
* with redesigned “recent events” section
* we want to show top 10 popular core datasets
* we want to show the latest 3 blog posts
* we want to have a input element that can be used to search datasets (it redirects to /search?q=... page)
