### ISSUE TITLE
User Dashboard - Create Mockups

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#333]
Based on #332  Create mockups for the outcome of the brainstorming session

## User Stories
* As a user, I want more clarity on the dashboard, so that I can find what I want from the dashboard
* As a user, I want the get data features on the dashboard, so that I can use it not just for publishing purposes
* As a user, I want a cleaner UI on the dashboard, that it helps me find what I want with minimal efforts.

## Acceptance Criteria
* [ ] Mockups are based on ideas selected in #332
* [ ] Mockups are reviewed by the team
* [ ] Mockups are relevant to the modern design of datahub and leads engaging user experience

## Tasks
* [x] Get mockups ready
* [x] Review and Feedback
* [ ] Updates based on the feedback

**Comment by tanvirchahal** [comment]
@anuveyatsu Please review 4 versions
https://invis.io/TPNC0QJH98U
https://invis.io/E2NC0QSAQ59
https://invis.io/TENC0R3Z46S
https://invis.io/F6NC0R7K2EP

**Comment by tanvirchahal** [comment]
# Actions while implementing (reviewed and agreed with anu)

* Use the Publisher Top Section from V3
* Use rest of the body elements from V1
* Include date for the blogposts
