### ISSUE TITLE
User Dashboard - Implement mockups

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#334]
Based on #333 Implement mockups and deploy the new dashboard

during the implementation consider https://github.com/datahq/datahub-qa/issues/167

## User Stories
* As a user, I want more clarity on the dashboard, so that I can find what I want from the dashboard
* As a user, I want the get data features on the dashboard, so that I can use it not just for publishing purposes
* As a user, I want a cleaner UI on the dashboard, that it helps me find what I want with minimal efforts.

## Acceptance Criteria
* [x] Design is as per the mockups
* [x] Design is implemented and tested across the devices
* [x] Design is approved by the team

## Tasks
* [x] Implement Design
* [x] Review and Feedback
* [x] Updates based on the feedback
* [x] Finalize the design
