### ISSUE TITLE
docs Page - Edit this page functionality

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#335]
Showing the "edit this page" button optional on docs section so we can turn it off for the about page

## User Stories
* As a datahub developer, I want to make the "Edit this Page" optional, so that I can gain more control on what can be edited and can not.

## Acceptance Criteria
* [x] Editing can be turned off on a doc
* [x] About Page is not editable

## Tasks
* [x] Update the docs functionality to be editable on choice
* [x] Ensure that About Page isn't editable
