### ISSUE TITLE
Pricing Page Updates

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#336]
Put two tables into separate tabs in the `/pricing` page @tanvir with clear separation

## User Stories
* As a user, I want separation between pricing page, so that I can clearly understand the pricing plans on datahub
* As a user, I want a clear separation on pricing page, so that I can distinguish between preimum data request and publish data pricings 

## Acceptance Criteria 
* [ ] Pricing Page is clearly separated
* [ ] Premium data request and Publish data pricing both are accessible to user without scroll
* [ ] Pricing of various datahub plans are clearly understandable 

## Tasks
* [x] Clean the page and separate the plans
* [ ] Review and Feedback
* [ ] Finalize
