### ISSUE TITLE
Graphs - Implement Graph Updates

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#338]
Based on #337,  implement the graphs to be cleaner and impressive 

## User Stories
* As a designer, I want the graphs to be in better colors, that it complement's datahub's color scheme
* As a user, I want cleaner graph UI, so that looking at the graphs is an easy and pleasant user experience for me

## Acceptance Criteria
* [x] Graph updates are implemented based on selected mockups
* [x] Graph updates provide cleaner UI
* [x] Graph updates align with datahub UI and provides a better UI experience

## Tasks
* [x] Implement graphs based on #337 
* [x] Feedback and Review
* [x] Finalize

**Comment by anuveyatsu** [comment]
FIXED see https://datahub.io/core/finance-vix graph
