### ISSUE TITLE
Use awesome pages icons in the meta tags

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#339]
Add the created icons to awesome pages 

# Acceptance Criteria 
* [x] Awesome icons are showing for each category

# Tasks 
* [x] Pick the awesome icon for each category
* [x] Resize and fit
* [x] Update the awesome repo and frontend code to support icons
