### ISSUE TITLE
Search Improvements - Brainstorming

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#345]
Brainstorm with the teammates regarding how the search can be improved

## User Stories
* As a user, I want more clarity on the search, so that I can find what I want from the search
* As a user, I want a cleaner UI on the search, that it helps me find what I want with minimal efforts.

## Acceptance Criteria
* [x] 10-15 ideas laid down
* [x] Ideas discussed with a reviewer
* [x] Relevant ideas are selected for implementation

## Tasks
* [x] Prepare moodboard
* [x] Prepare a list of ideas
* [x] Discuss ideas with team members
* [x] Select ideas to be implemented
