### ISSUE TITLE
Search Improvements - Mockups

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#346]
Create mockups based on the brainstorming on #345 

## User Stories
* As a user, I want more clarity on the search, so that I can find what I want from the search
* As a user, I want a cleaner UI on the search, that it helps me find what I want with minimal efforts.

## Acceptance Criteria
* [x] Mockups are based on ideas selected in #345 
* [x] Mockups are reviewed by the team
* [x] Mockups are relevant to the modern design of datahub and leads engaging user experience

## Tasks
* [x] Get mockups ready
* [x] Review and Feedback
* [x] Updates based on the feedback

**Comment by tanvirchahal** [comment]
https://invis.io/2YNNNH8R8NV
https://invis.io/PJISTSMNH2Z [selected]
https://invis.io/BRNNNHYSFGE

Considering the feedback in invision is minor updates,  the updates would be directly implemented during development.
