### ISSUE TITLE
Search Improvements - Implementation

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#347]
Implement the search design based on #346 

## User Stories
* As a user, I want more clarity on the search, so that I can find what I want from the search
* As a user, I want a cleaner UI on the search, that it helps me find what I want with minimal efforts.

## Acceptance Criteria
* [x] Design is as per the mockups
* [x] Design is implemented and tested across the devices
* [x] Design is approved by the team

## Tasks
* [x] Implement Design
* [x] Review and Feedback
* [x] Updates based on the feedback
* [x] Finalize the design

**Comment by tanvirchahal** [comment]
@anuveyatsu after discussing it with esteban, we have come to the conclusion that making "900 datasets" dynamic is not the priority for now and the search page can be delivered without it.

Let me know rest is fine with the page, we can proceed to merge and deploy

**Comment by anuveyatsu** [comment]
@tanvirchahal can we say "thousands of datasets" instead of 900? This is because we already have ~1100 public datasets + a number of unlisted and private datasets which gives us at least 2k I believe and this number is growing daily.
