### ISSUE TITLE
Use 'description' property of dpjson if readme is unavailable 

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#348]
As a Publisher, I want 'description' property of dpjson to be used as readme so that my datasets missing readme still have some short description for users to read and understand what is it about.

## Acceptance criteria

* [x] in showcase page, we use `description` property if readme is unavailable
* [x] we use `description` over readme snippet in the meta description
* [x] in search and publisher pages, we use `description` property if readme is unavailable

## Tasks

* [x] modify `views/showcase.html` in 2 places: short readme and full readme
* [x] modify `views/base.html` to use `description` over readme
* [x] modify `views/_snippet.html` to use `description` if readme is unavailable

**Comment by anuveyatsu** [comment]
FIXED
