### ISSUE TITLE
Fontawesome not visible on dashboard

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#349]
Font awesome icons are not showing on the dashboard

## Acceptance Criteria
* [x] Latest version of font awesome is working
* [x] Icons are visible in the dashboard

## Tasks
* [x] Inspect the problems with the font awesome
* [x] debug
* [x] resolve
