### ISSUE TITLE
User dashboard - Funnel people to premium data

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#352]
Make updates to the user dashboard, to increase the premium data requests

## User Stories
* As a user, I need an interface to raise data request, so that I can get in touch with datahub team to help me with datasets I need
* As a product owner, I need premium data on dashboard, so that I can draw requests for premium data from the dashboard

## Acceptance Criteria
* [x] Premium data marketed on dashboard
* [x] Clear call to action button to request premium data

## Tasks
* [x] Brainstorm the ideas
* [x] Implement the ideas 
* [x] Test & Deploy

**Comment by tanvirchahal** [comment]
premium data funnel created on the user dashboard page
