### ISSUE TITLE
Awesome Page - Brainstorming

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#353]
Brainstorm ideas to be implemented for awsome page 

## User Stories 
* As the DataHub team, we want to have more interactive layout of the awesome page so users arriving there have great UX.
* As user, I want a clear design for the awesome page, so that  I can clearly understand various types of data offered by Datahub 

## Acceptance criteria
* [x] Brainstorming session held
* [x] Ideas selected

## Tasks
* [x] brainstorm with esteban/anu
* [x] List out important ideas
* [x] Prepare moodboard

**Comment by tanvirchahal** [comment]
* [x] split the awesome landing page from inner data pages, so that landing page can be improved with html rather than plain md
* [x] use other ui elements rather than list
* [x] usage of icons for each category
* [x] show additional information like (tagline, datasets consisted)
* [x] lets say we show awesome data in boxes, last one we can do is for "Premium Data", can be used as a trick to sign users for  paid services
* [ ] Collections? Can we have an alternative like "Categories" - stick to collections
* [x] Improved design for better ui
* [ ] add search bar to assist users to find the datasets they are looking for - nope let's stick to the basics
* [x] overall design inspired from: inspire from 1st 
	https://trello-attachments.s3.amazonaws.com/5b3baaab4b0e6eee5e391c24/5b8d5a424929228db2988763/bf28b1c958b97d8aea4ce379e740f7c7/screencapture-zeit-co-cdn-2018-09-03-21_22_04.png 
	https://trello-attachments.s3.amazonaws.com/5b3baaab4b0e6eee5e391c24/5b8d5a424929228db2988763/3dd302cc2f92f90d0b1d5e8bd01aa6f8/Captured.PNG
* [ ] include keywords for better seo, something like :  (not sure, see it later during implementation?)
	https://trello-attachments.s3.amazonaws.com/5b3baaab4b0e6eee5e391c24/5b8d5a424929228db2988763/c1f05dbadc2f82b965200f4c8a889c2f/4.png
* Moodboard: https://trello.com/c/xrp9GAP9/9-examples


Actions:
* split the awesome landing page from inner data pages, so that landing page can be improved with html rather than plain md
* better ui
* show additional information like (tagline, datasets consisted,icons)
* designed list can be inspired from the docs
