### ISSUE TITLE
Awesome Page - Mockups

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#354]
Create mockups based on brainstorming done in #353 

## User Stories 
* As the DataHub team, we want to have more interactive layout of the awesome page so users arriving there have great UX.
* As user, I want a clear design for the awesome page,so that  I can clearly understand various types of data offered by Datahub 

## Acceptance criteria
* [x] Mockups are reviewed
* [x] Best mockup is selected

## Tasks
* [x] Create Mockups
* [x] Review with team
* [x] Compare and select the best version

**Comment by tanvirchahal** [comment]
https://invis.io/WQNV80DMVYK (chosen)
https://invis.io/85NV80S4KAG
