### ISSUE TITLE
DataFactory - New Graphics

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#356]
Create new graphics for /data-factory   for why-datafactory and what does data factory contain

## User Stories
* As a user, I want improved graphics, so that I can be better informed about the data factory offerings
* As a designer, I want better graphics on the data factory, so that the overall page appeals more attractive to the users

## Acceptance Criteria
* [x] New Graphics implemented
* [x] Reviewed and Finalized

## Tasks
* [x] Create Graphics
* [x] Review with team
* [x] Updates based on feedback

**Comment by tanvirchahal** [comment]
new graphics can be seen on
https://datahub.io/data-factory
