### ISSUE TITLE
Update profile pictures for users on dataset page

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#358]
The profile pictures of users like /sports-data are simple gradients,  change them to something interesting

## Acceptance Criteria
* [x] Profile Pictures are updated on each user
* [x] Profile pictures are relevant and well designed

## Tasks
* [x] Brainstorm with Anu regarding all the users that need a profile picture upgrade
* [x] Create interesting pictures for each
* [x] Update the profile pictures

**Comment by tanvirchahal** [comment]
Profile Pictures for  Machine Learning, Sports, and World Bank were requested

https://drive.google.com/drive/folders/1X6M_28ibCTF8XlM_jBJZ0EU3fVYFTeMD?usp=sharing

Personal preference is white

**Comment by anuveyatsu** [comment]
@tanvirchahal yes, white works great! Not sure which one to choose for machine learning.

**Comment by tanvirchahal** [comment]
@anuveyatsu i think v1_1  looks sweet. 
Let me know how to update these on the specific users :)

**Comment by tanvirchahal** [comment]
gravatars added example:
https://datahub.io/sports-data
