### ISSUE TITLE
Run frontend locally without need of internet connection

### ISSUE THREAD

**Issue by Mikanebu** [datahq/frontend#36]
When loading front and showcase pages (for local development), we get package data directly from bitstore that is not great as we are making unnecessary API calls, spending more time to reload pages and also we cannot work without internet connection.

We want to have `/public/fixtures/` directory fixture packages that will be used for the front page (3 for the most popular packages and 3 for tutorial packages). We also want to consider size of packages as we do not want to have large files in our fixtures.

## Acceptance criteria

* [x] i can run server according to the readme without any error
* [x] i can run server and get rendered main pages without internet connection

## Tasks

* [x] Create directory  `/public/fixtures/`  and create data packages respectively 3 for the most popular packages and 3 for tutorial packages
* [x] Check size of packages, they should not contain large files 
* [x] Run server and test showcase page without internet connection

**Comment by anuveyatsu** [comment]
FIXED in #37
