### ISSUE TITLE
Update T&C Legal email address

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#364]
update our T&Cs legal email address from datahub-legal@datopian.com to office@datopian.com

# Acceptance Criteria
* [x] Email address is updated
* [x] Clicking on the link opens default email app

# Tasks
* [x] Update the link
* [x] Test & Deploy
