### ISSUE TITLE
Analytics - Measure datahub traffic

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#369]
Do an analysis of datahub.io with the information from Google Analytics. Study and document the changes that have been observed in the user's behavior for the frontend changes

## User Stories
* As Product Owner, I want an analysis of Google Analytics data from last 3 months, so that I can draw conclusions of the traffic flow on the website
* As Tanvir, I want to analyze changes in user's behavior in the new design, so that I can figure out ways to improve engagement

## Acceptance Criteria
* [x] A report providing concrete evidence of user's behavior
* [x] Meeting with concerned team members to draw conclusions
* [x] Formulate the necessary steps to be taken to improve on the current user behavior on the website to increase engagement

## Tasks
* [x] Analyse Google Analytics data of last months
* [x] Inspect the usage patterns
* [x] Draw reports comparing the user's behavior

**Comment by tanvirchahal** [comment]
Findings:
* comparing aug vs july (traffic up by 18.92%)
* 1-12sept vs 1-12aug   (3.30% increase)
* Top country visited  US, IND, UK
    * we can create country specific datasets

* Max people reaching out to search from home
* Comparing new vs old, pageviews up by 17%,avg time on page increased 15% (/search)   (3sep-9  vs 20aug - 26)
* pageviews on /requests have increased by 20%   (3sep-9  vs 20aug - 26)  (good sign as we have linked it from search and various other places)
* biggest landing page  but at the same time biggest exit page /core/country-list   (need more retention)
* page speed scores require improvement , especially top 2
* homepage has high avg time, but high bounce rate as well
* no perfect way to track premium-data requests currently except KPIs for the interacting users
* checking the user flow from /home ,  not enough redirects /requests or premium reqeuests

* Notes
    * check if we can compare cali vs searches
    * @ tanvir - we can track what people were searching for https://www.entrepreneur.com/article/276722 
    * measure bounce rate and keep a track in kpis
    * /search is getting more traffic, tweak the hero section to empower /search more as users seem to be most interested in finding the data
    * reduce the exits from /core/country-list by motivating them to "search" with graphics and powerful suggestion
    * improve page speed to get in Google's green zone (proper minimfication of the files - CCS/js, server response times, leverage browser caching, optimise images)
    * discuss with anu , either improve the kpis to measure or install google analytics (we need to see how many people bounce off)
    * Devices 80% desktop, 19% smartphone, 1%Tablet
