### ISSUE TITLE
Analytics - Monitor Device Usage of Datahub

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#370]
Analysis on the device usage pattern of datahub

## User Stories
* As a designer, I want to monitor I want to measure device usage of datahub, so that I can find out which are the most popular devices among website users
* As a designer, I want to find out devices used by datahub users, so that I can optimize the website for the better experience on the majority of device screens and sizes.

## Acceptance Criteria
* [x] A report providing concrete evidence of device usage
* [x] Meeting with concerned team members to draw conclusions
* [x] Formulate the necessary steps to be taken to improve on the current user behavior on the website to increase engagement

## Tasks
* [x] Analyse Google Analytics data of last months for devices used
* [x] Inspect the usage patterns from various devices
* [x] Draw conclusions if focus on non-desktop screens is required

**Comment by tanvirchahal** [comment]
* 80% of the users on datahub are desktops
* tablets being lowest at 1%
* very high bounce rate from mobile 
* decreasing mobile user trend from last few months (see july vs aug)
* Pages are already mobile friendly and do not need any further improvements, 
https://search.google.com/test/mobile-friendly?id=-Dm5wCznSg0_pz_is_cuhA
* sept 30% users have been mobile, (need to measure this trend continously to see if mobile users are really coming or not)
* 2018, 18% users are mobile (not so significant) 
* since the redesign the number of mobile users approx 30%  (new design is attracting users)

### Final Notes
* the mobile users is still a low number to enforce any further actions
* keep an eye on weekly/monthly mobile trends to see if the mobile traffic on datahub is on a continuous rise/fall
