### ISSUE TITLE
Rename Awesome to Collections

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#371]
Rename the awesome to collections

## Acceptance Criteria
* [x] /Awesome renamed to /Collections
* [x] All the headings replaced from awesome to collections

## Tasks
* [x] Rename the headings and routes
* [x] Ensure links working properly
* [x] Test & deploy
