### ISSUE TITLE
Homepage - have clients we have worked with

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#372]
On homepage add the list of clients that we have worked with

## User Stories
* As a product owner, I want to show recent clients, so that I can showcase our work on the website
* As a product owner, I want to show recent clients, so that company look more credible,trustable and datahub team looks more experienced in taking care of the clients

## Acceptance Criteria
* [x] Ideas are brainstormed
* [x] Mockups depicting clear area for recent clients
* [x] Recent Clients section is added to the website

## Tasks
* [x] Grab a list of clients from Esteban
* [x] Brainstorm design ideas
* [x] Mockup alternative designs
* [x] Implement 
* [x] Deploy

**Comment by tanvirchahal** [comment]
https://invis.io/HVO003AWG2M
https://invis.io/E2O003GP3NJ
https://invis.io/PMO003QKSD9
https://invis.io/VWO003T9FD5
