### ISSUE TITLE
Homepage - Table to link to real datasets

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#373]
The table on the homepage doesn't link to any real dataset, add a link where user can see the dataset in action

## User Stories
* As a user, I want a link to original dataset from the homepage table, so that I can explore more about the data that is shown on the homepage

## Acceptance Criteria
* [x] Link working to the full dataset page 

## Tasks
* [x] Find a matching dataset to the homepage table 
* [x] Add link to the hompage table, leading to the dataset page
* [x] deploy
