### ISSUE TITLE
Collections - Fix bug for link to data request

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#374]
Link from collections description text to the /requests page

## Acceptance Criteria
* [x] Description text has a link to /request page

## Tasks
* [x] Add a link to the page
* [x] Test and Deploy
