### ISSUE TITLE
Datasets - Datahub Certified - Implementation

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#377]
Implementation based on mockups of #376 

## User Stories
* As a user I want to know if the data is quality (ie up to date and I can keep rely on it, reliable - it’s been looked after, from an authoritative source so that 
  - I know that it’s well structured and in the a format I can use
  - I can be secure in relying on it (The data is correct)
  - If I base my analysis on this I will get insight and my derived work is accurate and timely (and I don’t need to clean the data up)

* As a user who wants to get datasets, I can rely on the data overall so I know I can depend on it overtime

## Acceptance Criteria
* [x] Design for datahub certified is ready
* [x] Code is approved and pushed in branch for backend work

## Tasks
* [x] Implement design
* [x] Test and feedback
* [x] Finalize

**Comment by tanvirchahal** [comment]
impelemntation in branch dh-certified
