### ISSUE TITLE
Awesome/Collections - Subpage Redesign Mockups

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#379]
Create mockups based on #378 

## User Stories
* As user, I want subpage design to look similar to the collections dashboard, so that my user experience stays consistent
* As product owner, I want the subpage design to be better, to support premium data and better user experience
* As Tanvir, I want the subpage design to redesign, so that it can increase the user satisfaction and move to datahub's new design approach

## Acceptance Criteria
* [x] Mockups are created
* [x] Final mockup is chosen

## Tasks
* [x] Create mockups
* [x] Review and feedback
* [x] Finalize mockup
