### ISSUE TITLE
Awesome/Collections - Subpage Redesign Implementation

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#380]
Implement the collections subpage design based on #379 

## User Stories
* As user, I want subpage design to look similar to the collections dashboard, so that my user experience stays consistent
* As product owner, I want the subpage design to be better, to support premium data and better user experience
* As Tanvir, I want the subpage design to redesign, so that it can increase the user satisfaction and move to datahub's new design approach

## Acceptance Criteria
* [x] Subpage redesign is implemented as per mockups
* [x] Subpage redesign is tested and deployed

## Tasks
* [x] Design and develop
* [x] Review 
* [x] Updates as per feedback
* [x] Deploy
