### ISSUE TITLE
Requests - Include More Details

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#381]
Include:  Company, NGO/charity, Student, Academic/researcher, Personal)

## User Stories
* As a sales employee, i want to know more about requestor, so that I can easily segment the requests and provide better assistance
* As a product owner, I want to know the originator better, so that I can tailor the request to the needs of the request

## Acceptance Criteria
* [x] Ideas brainstormed
* [x] New inputs for more details included in the form

## Tasks
* [x] Brainstorm with esteban
* [x] Implement
* [x] Test the inputs working good
