### ISSUE TITLE
Homepage - Replace core data with collections links

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#390]
Replace the core data with collections

## Acceptance Criteria
* [x] Replaced Find Data link with collections
* [x] Link leading to /collections page

## Tasks
* [x] Update the link
* [x] Test
* [x] Deploy
