### ISSUE TITLE
Pricing Page - Add Premium Data Offerings

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#392]
Add the datahub premium offering popup when user decides to choose contact us

## User Stories
* As a user, I want the premium data request input on pricing, so that I can reach out the team for the services
* As a user, I want the premium data request input on pricing, so that I don't have to fill out the contact form which is confusing. 

## Acceptance Criteria
* [x] Added the popup
* [x] premium data popup working

## Tasks
* [x] Add the popup
* [x] make it work when the user clicks contactus
* [x] Test
* [x] Deploy
