### ISSUE TITLE
DH Certified - Logical Impelemntation

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#395]
As a user I want to know if the data is quality (ie up to date and I can keep rely on it, reliable - it’s been looked after, from an authoritative source so that 
  - I know that it’s well structured and in the a format I can use
  - I can be secure in relying on it (The data is correct)
  - If I base my analysis on this I will get insight and my derived work is accurate and timely (and I don’t need to clean the data up)

As a user who wants to get datasets, I can rely on the data overall so I know I can depend on it overtime

## Acceptance Criteria
* [x] Criteria for a certified dataset is finalized
* [x] Good Datasets getting certified logo
* [x] Code is integrated to the backend and tested

## Tasks

* [x] Do analysis

## Analysis

Think this should be defined in datapackage.json as a new property and later used by frontend to decide to display logo or not. Eg

```
{
  "name": "finance-vix",
  "certifiedForDatahub": true/false,
  "resource": [...]
}
```

Question is how to avoid others to just declare that property in dp.json of their dataset. That is not something we controll: anybody can define anything in the datapackage.json of their datasets, meaning they can just set `"certifiedForDatahub": true,` and dataset would become certified.

To avoid above, I think we should include that info in the user plans. So together with `Max Public Storage`, `Max Private Storage` and `Max Dataset Num` we will have `certified` -> default to False`. This will allow us to determain user is certified or not and explicitly modify `certifiedForDatahub` propery when processing the dataset. 

Eg: in the specstore:
```
# in specstore
def upload(token, contents,
           registry: FlowRegistry,
           verifyer: auth.lib.Verifyer,
           config=CONFIGS):
    ...
    permissions = verifyer.extract_permissions(token)
    verified = permissions.get('verified', False)
    config['verified'] = verified
    pipelines = planner.plan(revision, contents, **config)

# in planner 
def _plan(revision, spec, **config):
    ...
    final_steps = [
        ('add_metadata', {'certified': config.get('certified')}),
    ]

```
This will allow us to overwrite `certifiedForDatahub` even if user sets it to be True manually.

### Changes in plans

Currently `Plans` table in our database monitors only max public/private storage and number of datasets. To achieve above we will probably need to add new column to track certified Flag

**Comment by akariv** [comment]
What we really want is to be able to mark a dataset as 'certified', and to do that we want to mark users as 'trusted' - as in 'trusted to mark datasets as having good quality'. 
This is a bit different than what is described, where all datasets from a trusted user are automatically certified (which might not be the case at all).

**Comment by zelima** [comment]
@akariv As we decided, for now, this should happen manually. We will start with internal packages and update statuses one by one manually. Later we will have `request` button or similar for non-datahub users to ask us for review their datasets to gain the certified badge.

## How we can do this

The current version of metastore response includes the following data

```
{
  "id": id,  // flow id
  "name": name, // dataset name
  "title": title,  // dataset title
  "description": description,  // description
  "datahub": datahub,  // datahub related metadata
  "datapackage": datapackage  // datapackage.json
}
```

As a solution, we could add another property here `certified` flag that will be either True or False. 

## How to save it in metastore.

We do not want this to be a part of datapackage.json pushed by the users, because then they can easily include `certified` property in there and make their datasets certified. 

So, for now, we will do this manually probably directly hitting elasticsearch endpoint or use specstore's `datasets` module to export updated version of metadata. Eg

```
from flowmanager import datasets

for open(certified_datasets.csv):
    metadata = request.get('datahub.io/core/finance-vix/datapackage.json')
    metadata[certified] =  True
    datasets.send_dataset(metadata)
```

We can create gist of this and save it somewhere so that everybody can re-use it. Or keep script Eg in deploy repo and run the script by travis on every change with proper environment variables.

Question: What should we do with the automated ones? The processors will generate the new datapackage.json every time they are processed. Doing manually this every day may become a torture

**Comment by akariv** [comment]
@zelima a few questions:
- Why metastore and not specstore API - i.e. https://api.datahub.io/source/core/finance-vix/latest ?
- Will this get overwritten whenever we upload a new revision? For the specstore I can say for sure that if we add a new property to the `Dataset` model it won't be modified on uploads.
- Won't your code snippet modify the datapackage.json that's returned by the API?

**Comment by zelima** [comment]
@akariv 
> Why metastore and not specstore API - i.e. https://api.datahub.io/source/core/finance-vix/latest ?

Not sure. This was my initial thought as I was imagining the badge should appear on search page: people search for stuff and choose the certified ones. So since search is getting data from metastore API, thought it would be the best to include that info into in its response (as we don't want it to include in dp.json).

But now I see we might need it in both search page and showcase. So we might have to modify them in both?

> Will this get overwritten whenever we upload a new revision? For the specstore I can say for sure that if we add a new property to the Dataset model it won't be modified on uploads.

With the approach I proposed above, yes - it will be overwritten and not sure how to handle that. 

But as I understand you recommend to add another column to `Datasets` table and manually modify its values manually, right? This makes more sense and yes, it will not modify anything on uploads. Just what to do with `metastore`?

> Won't your code snippet modify the datapackage.json that's returned by the API? 

Correct, that snippet is wrong. Also after newly proposed solution it does not make sense at all

**Comment by zelima** [comment]
@tanvirchahal @anuveyatsu DH certified is live in the testing environment. You can find certified property in both specstore and metastore API

## Specstore API response

```
"error_log": [...],
"id": "datahq/datahub-kpis/75",
"logs": null,
"modified": "2018-10-09T11:28:55.395198",
"pipelines": {},
"spec_contents": {},
"state": "...",
"stats": {}
"certified: true"
```

## Metastore API response

```
{
"datahub": {},
"datapackage": {},
"description": "Total Population - Both Sexes. De facto population in a country, area or region",
"id": "core/population-growth-estimates-and-projections",
"name": "population-growth-estimates-and-projections",
"title": "Population Growth"
"certified": true
},
```

Please refactor frontend accordingly and test few datasets in testing before moving to production

**Comment by zelima** [comment]
FIXED

**Comment by anuveyatsu** [comment]
@tanvirchahal do we have a frontend issue for this?

**Comment by tanvirchahal** [comment]
@anuveyatsu Have an issue for creating the design https://github.com/datahq/frontend/issues/377

**Comment by anuveyatsu** [comment]
@tanvirchahal ok, please, create another issue for implementation - we need to use that `certified` property in showcase, search and publisher pages.

**Comment by zelima** [comment]
@tanvirchahal @anuveyatsu also on search page probably
