### ISSUE TITLE
Pagespeed Improvements - Google Insights

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#399]
Improve the pagespeed of the webiste
Google has indicated site speed (and as a result, page speed) is one of the signals used by its algorithm to rank pages.
https://developers.google.com/speed/pagespeed/insights/?url=datahub.io

## User Stories
* As an owner, i want to improve google speed, so that i can get better speed rating and seo traffic from google 
* As a designer, I want to improve the page speed , so that users can have a better experience on the website 

## Acceptance Criteria
* [x] Google page speed is measured
* [x] Page speed is improved

## Tasks
* [x] Measure the speed
* [x] Make improvements
* [x] Measure
* [x] Deploy

**Comment by tanvirchahal** [comment]
speed score taken up from 58 to 80 with lossless optimizations
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fdatahub.io%2F&tab=desktop
