### ISSUE TITLE
Frontend data "API"

### ISSUE THREAD

**Issue by rufuspollock** [datahq/frontend#40]
Support API like ... read https://github.com/okfn/data.okfn.org-new/issues/6

## Acceptance criteria

  * [x] /core/finance-vix/r/{name-or-index-in-list}[.csv,.json]
    * [x] .csv => redirect to pkgstore url for that file (with 302 temporary)
    * [x] .json => same ...
      * [x] pkg store for json files is /latest/.datahub/data-json/{path-for-csv-including.csv}.json 
    * [ ] (Low priority) no extension - render html page with resource info, link to parent package and a preview of the data ...

## Tasks

* [x] create a new route to handle the path `/core/finance-vix/r/{name-or-index-in-list}[.csv,.json]`
* [x] workout and create logic to identify needed url and redirect to there

**Comment by anuveyatsu** [comment]
FIXED - we're leaving html versions for later as it is not a priority atm.
