### ISSUE TITLE
potential security vulnerability in dependencies

### ISSUE THREAD

**Issue by zelima** [datahq/frontend#402]
Github says 

> We found a potential security vulnerability in one of your dependencies.
A dependency defined in package-lock.json has known security vulnerabilities and should be updated.

## Acceptance Criteria

* [x] We detailed have analysis what's happening here
* [ ] replace dependency if possible

## Tasks

* [x] Do the analysis
* [x] re-generate package.json and package-log.json and update the repo

**Comment by anuveyatsu** [comment]
Closing as FIXED. 2 dependencies (indirect) still have potential vulnerability issues but there is no way to fix it as it should be fixed upstream (by maintainers of libraries). We also don't think that the code is actually used in our repo.

Dependencies that have issues:

* cryptiles (suggested to upgrade to v4.1.2 but we're not using this lib directly)
* string.js (no suggestion for fix)
