### ISSUE TITLE
Solve Jquery Bugs

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#407]
Sticky bottom on showcase page not showing up

## Acceptance Criteria
* [ ] Console errors removed
* [ ] Stick bototm functionality restored

## Tasks
* [ ] Find the error
* [ ] Apply Fix
* [ ] Deploy
