### ISSUE TITLE
New Form inputs are submitted to fresdesk

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#408]
Ensure all the newly added form inputs are getting sent to freshdesk, tanvir, anu

## Acceptance Criteria
* [ ] Inputs getting received in freshdesk
* [ ] Data is being correctly transferred without any missing field

## Tasks
* [ ] Update the code to send all inputs data to freshdesk
* [ ] Test
* [ ] Deploy
