### ISSUE TITLE
Subpages Speed Improvements

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#409]
Improve the google pagespeed of the subpages
Implement Optimizations like Leverage Browser Caching, compression etc.

## Acceptance Criteria
* [ ] Page speed increased above 80%
* [ ] No functionality / quality is lost during the optimization

## Tasks
* [ ] Find out the current scores
* [ ] Apply browser caching
* [ ] Page compression techniques
* [ ] Test
* [ ] Deploy
