### ISSUE TITLE
Premium Data in the center of website- Implementation

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#412]
Implement the updates based on Phase 1 mockups #411 

## Acceptance Criteria
* [x] Premium data is put in better position at the website
* [ ] Updates are deployed on live
* [x] Updates are ready to be measured

## Tasks
* [x] Implement
* [x] Deploy
* [x] Review and Feedback
* [x] Finalize
