### ISSUE TITLE
Improve meta data for “data hub” and datahub searches for Google

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#423]
## User Stories
* As datahub team member, I want to improve meta data for the website, so that datahub can drive more traffic
* As Datahub developer, I want to improve meta data for datahub, so that it can reflect on more relevant search engine searches.

## Acceptance Criteria
* [ ] Updates made to meta descriptions
* [ ] Updates Deployed

## Tasks
* [ ] Create a plan for the descriptions to be updated
* [ ] Make the updates
* [ ] Check if we can modify relevant links shown during google search
* [ ] Deploy
