### ISSUE TITLE
Premium Offering Page - Implementaiton

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#425]
Implement the mockup approved by the team

## User Stories
* As a user, I want a dedicated premium page, so that I can be completely educated about the datahub's offerings
* As a user, I want a dedicated premium page, because the modal is not informative and leaves confusion between data request and premium data
* As a datahub developer, I want to create a dedicated premium page, to put premium in the center of the website and be able to maximize the traffic for premium

## Acceptance Criteria
* [ ] Page developed
* [ ] UAT done
* [ ] Page deployed

## Tasks
* [ ] Develop the page based on mockups
* [ ] Sort out the content with esteban
* [ ] Test and Feedback
