### ISSUE TITLE
Fix for icons not working in the recent events section of the publisher page

### ISSUE THREAD

**Issue by tanvirchahal** [datahq/frontend#426]
Icons are not working and need to be resolved

## Acceptance Criteria
* [x] Problem with the icons resolved
* [x] Fix pushed to live

## Tasks
* [x] Find the problem
* [x] Resolve 
* [x] Test and Deploy
