### ISSUE TITLE
Use the resolver for showcase page route

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#45]
Once resolver is working wire up it into the frontend. Use the resolver for /{publisher}/{name} pathes

## Acceptance criteria

* [x] loading showcase page uses `userid` & `packageid` from resolver api

## Tasks

* [x] refactor `routes/index.js` to use `api.resolver` with owner and name
* [x] add new method in `lib/index.js` - `resolve(path_)`
* [x] add new mocked api
* [x] add new test

**Comment by anuveyatsu** [comment]
FIXED
