### ISSUE TITLE
Publisher profile page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#47]
Publisher profile page - list all their datasets, show them how much space they are using (metastore API)

## Acceptance criteria

* [x] I can go to `/core` and see info about core publisher
  * [x] how many packages it has
  * [x] list of all packages published (we're limiting to 20)
  * [x] I can search through the list of packages that the publisher has (among 20)

## Tasks

* [x] refactor routes to use the new method by passing owner
* [x] refactor the template
* [x] implement filtering packages (should happen in browser using JS)

## Analysis

```javascript
router.get('/:owner', (req, res) => {
  const token = req.cookies.jwt
  const packages = await api.getPackagesFromMetastore(`datahub.owner=${req.params.owner}`, token)

  res.render('owner.html', {
    title: req.params.owner,
    packages
  })
})
```

**Comment by anuveyatsu** [comment]
FIXED - see https://testing.datahub.io/core
