### ISSUE TITLE
Search page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#52]
Use metastore API for the search page

## Acceptance criteria

* [x] I can search for any text and get list of packages that matches

## Tasks

* [x] implement `/search` router to use metastore api wrapper function
* [x] refactor `search.html` template

**Comment by anuveyatsu** [comment]
FIXED, see https://testing.datahub.io/search?q=co2
