### ISSUE TITLE
Metastore API wrapper

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#54]
We want to have `metastore` API wrapper method in `DataHubApi` class so we can query the API to get a list of packages.

## Acceptance criteria

* [x] I can do `DataHubApi.getPackagesFromMetastore(myQuery)` to get list of packages for any given query.

## Tasks

* [x] create a new method `getPackagesFromMetastore` that takes following arguments:
  * [x] `query` (any query according to API docs)
  * [x] `token` (for cases when I want to get my private packages as well)

## Analysis

```javascript
// in DataHubApi class:
async getPackagesFromMetastore(query, token) {
  const options = token ? {headers: {'Auth-Token': token}} : null
  const url = `${this.DATAHUB_API}/metastore/search?${query}`
  const response = await fetch(url, options)
  if (response.status !== 200) {
    throw {
      name: 'BadStatusCode',
      message: `Bad response from metastore for ${query}`,
      response
   }
}
return response.json()
```

**Comment by anuveyatsu** [comment]
FIXED - now can pass any query to `DataHubApi.getPackagesFromMetastore(myQuery)` and get response from metastore api.
