### ISSUE TITLE
Misc improvements from 5 Aug 2017

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#55]
## Tasks

* [x] nice coloured gravatar by default (rather than ugly one) - set default gravatar to the beautiful sylvie image - see http://en.gravatar.com/site/implement/images/
* [ ] profile page
  * [x] remove margin on lhs (gravatar and logo should be aligned)
  * [x] gravatar should have no border
  * [ ] show "member since" using auth db info
  * [ ] (to think about) layout of the page (big gap between gravatar and list - maybe go for two items per column and more card like)
  * [x] Number of datasets should be elegant - black circle with white number and same size as title (cf logo style and text)
    * [x] Set title tag so hover says: "{{number}} published datasets" (i.e. 89 published datasets or whatever)
  * [x] Data Packages => Datasets
* [ ] use owner in standard location datahub.owner rather than invent ourselves
* [x] convert short readme into plain text in search/publisher pages - https://github.com/datahq/frontend/commit/90c7eded999347268bcc03c9d8f079d0106746cb
* [x] change main text in the front page
* [x] have arrow down in the hero element of front page that scrolls down to showcase packages section

**Comment by anuveyatsu** [comment]
FIXED.
