### ISSUE TITLE
One of the example packages is empty 

### ISSUE THREAD

**Issue by zelima** [datahq/frontend#59]
in tutorials section on the front page, there are 3 example packages and geojson tutorial is empty - not actually showing anything. Not much useful as an example. 

## Acceptance criteria

* [x] we don't have dataset that is not working as an example (at least on front page)

## Tasks

* [x] refactor `extendedToLogical` method so it handles `geojson` or any other non-tabular resources
* [x] replace `s-and-p-500-companies` => `co2-ppm`

**Comment by anuveyatsu** [comment]
@zelima @rufuspollock I suggest using https://testing.datahub.io/examples/transform-examples-on-co2-fossil-global here - so we can show transform features.

Also, I suggest replacing core package:

* [s-and-p-500-companies](https://testing.datahub.io/core/s-and-p-500-companies) => [co2-ppm](https://testing.datahub.io/core/co2-ppm) - because of graph and number of resources

**Comment by rufuspollock** [comment]
@anuveyatsu why is geojson empty though?

@anuveyatsu on other two suggestions -- it sounds good (once we fix geojson - we may want geojson and the others)

**Comment by anuveyatsu** [comment]
FIXED see http://datahub.io/
