### ISSUE TITLE
When logged in, should have avatar and menu instead of logout

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#67]
When i login, rather than say logout should have avatar, which should have a popover menu with following links:

* Dashboard
* Logout

## Acceptance criteria

* [x] when logged in, I see my gravatar on the top-right of the page
* [x] when logged in, I can click on my gravatar and see popover menu with `dashboard` and `logout` links

# Tasks

* [x] refactor `base.html` template
* [x] refactor sass styles

**Comment by anuveyatsu** [comment]
FIXED

<img width="1280" alt="screen shot 2017-08-11 at 22 13 04" src="https://user-images.githubusercontent.com/17809581/29221911-52a692ac-7ee2-11e7-8ad8-d00f878643a6.png">
