### ISSUE TITLE
Login button rework

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#68]
We want to have just a text saying login (no logos etc.), on click it should open modal popup where users can select signup/login methods (just github for now). See example from https://zeit.co/login . It should say "To sign up or log in, you can use your existing GitHub account:" - and there should be button with github logo saying.

## Acceptance criteria

* [x] on navbar there is no github/google logos, just a link saying 'LOGIN'
* [x] that link redirects to `/login` page where I can see more info about signup/login and do login

## Tasks

* [x] refactor `/routes/index.js`
  * [x] `/login/:provider` => `/login` and renders `login.html`
  * [x] refactor tests
* [x] template work
  * [x] create and develop `login.html` template
  * [x] work on stylings

**Comment by anuveyatsu** [comment]
FIXED
<img width="1280" alt="screen shot 2017-08-14 at 11 54 37" src="https://user-images.githubusercontent.com/17809581/29259834-5f5f1080-80e7-11e7-8fef-e21f67ad9cb0.png">
