### ISSUE TITLE
Links rework

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#69]
Links should be consistent in color and style.

* regular links (e.g., links in the text):
  * `color: #ff7900`, `text-decoration = underline`, `on hover = nothing`
* special links (e.g., username, file name):
  * `color: black`, `text-decoration: none`, `on hover: underline`
* large links (e.g., titles):
  * `color: black`, `text-decoration: underline`, `on hover: nothing`

## Tasks

* front page:
  * [x] banner links - regular
  * [x] sign up to request early access » - regular
  * [x] explore more - regular
* publisher/search page:
  * [x] by core - special (should say just core)
* showcase page:
  * [x] in Data Files, file names - special
  * [x] download link (both csv and json) - regular
  * [x] download icons - regular (and bigger)

**Comment by anuveyatsu** [comment]
FIXED, see http://datahub.io/
