### ISSUE TITLE
Integrate user (publisher) docs here

### ISSUE THREAD

**Issue by rufuspollock** [datahq/frontend#73]
Currently user docs and developer docs are at docs.datahub.io. We want to move user docs here so that:

* Coherent - Common (elegant) theme (docs theme not as nice and contrasts)
* Easy to find - integrate app and key user docs

## Acceptance criteria

* [ ] All user (publisher) docs on docs.datahub.io are live at /docs/... on datahub.io

## Tasks

* [x] Decide on docs structure in this repo and whether we have frontmatter or not (0.5)
  * No frontmatter needed for now - we can use first heading as the title ...
* [x] Research libraries and approach for implementing (0.5)
  * Front matter parser: https://github.com/jonschlinkert/gray-matter
  * toc: https://www.npmjs.com/package/marked-toc
  * We are using marked so stuck with that but also looked at remarkable
* [x] Implement (2) - can port from old data.okfn.org
  * [x] Test ...
  * [x] Template + router
    * [x] custom markdown ... - maybe we need switch to markdown-it #75
  * [x] ~~mermaid js - bespoke css and js on a given page ... (is it worth it limiting it per page or ...?)~~ - not needed for now as have no diagrams that require this (and think it should not be needed).
* [x] Move over user docs from docs.datahub.io (2)
  * [x] getting started
  * [x] cli
  * [x] views
  * [x] core data

## Analysis

Planned sections:

* Getting started
* Examples
* Features
* Data Packages

Old publisher docs:

```
index.md --> getting-started/
cli.md --> features/data-cli.md
core-data-curators.md --> core-datasets/curators.md
core-datasets.md --> core-datasets.md
views.md --> features/views.md
```

**Comment by rufuspollock** [comment]
FIXED though no docs home page properly yet see #82. Also migrating more docs from data.okfn.org is #79
