### ISSUE TITLE
Switch to markdown-it from marked

### ISSUE THREAD

**Issue by rufuspollock** [datahq/frontend#75]
Why?

* Commonmark by default
  * fenced code blocks by default
* Very extensible with plugins and this means support for stuff like:
  * toc - https://www.npmjs.com/package/markdown-it-table-of-contents
  * info sections

Other projects I've looked at seem to use it / consider it e.g. [hackmd](https://github.com/hackmdio/hackmd/blob/master/package.json#L61)

## Acceptance criteria

* [x] we use `markdown-it` to convert markdown into html
* [x] supports headers as anchors
* [x] supports block containers (`:::info`)

## Tasks

* [x] use `markdown-it` instead of `marked` here - https://github.com/datahq/frontend/blob/master/lib/utils/index.js#L58
* [x] user `markdown-it-anchor` for supporting headers as anchors
* [x] use `markdown-it-container` for supporting block containers
* [x] ensure all tests are passing

**Comment by rufuspollock** [comment]
@anuveyatsu have we checked markdown-it can do everything we are using marked for see e.g. the docs route for an example of full usage.

**Comment by anuveyatsu** [comment]
@rufuspollock yes.
Headings can have an embedded anchor tag like on GitHub using plugins:
* https://github.com/valeriangalliat/markdown-it-anchor
* https://github.com/medfreeman/markdown-it-toc-and-anchor

`markdown-it` also discussing having it as built-in feature here - https://github.com/markdown-it/markdown-it/issues/28 - but probably not soon.

Re other options we're using with `marked`:
* GFM and tables are enabled by default in `markdown-it`
* smartLists - not sure what exactly does this option in `marked` - behaves similarly to me.
* smartypants - there is something similar called `typographer`

**Comment by anuveyatsu** [comment]
FIXED. We do CSS stuff in a separate issue, e.g., for block containers. Atm, behavior is as the following:

```
:::info
some info message
:::
```
==>
```html
<div class="info">
  <p>some info message</p>
</div>
```
