### ISSUE TITLE
Migrate old data.okfn.org docs

### ISSUE THREAD

**Issue by rufuspollock** [datahq/frontend#79]
Migrate old data.okfn.org docs to this new site.

Old data.okfn.org docs - https://github.com/okfn/data.okfn.org-new/tree/master/doc:

```
api.md   --> ignore (basically empty)
core-data-curators.md  --> ignore obsolete (have a new version)
csv.md --> data-packages/csv.md
data-package.md --> data-packages.md
tabular-data-package.md --> data-packages/tabular.md
index.md --> ignore (will have a new index.md)

# these can move under data-packages (but need links correcting)
publish.md
publish-any.md
publish-faq.md
publish-geo.md
publish-online.md
publish-tabular.md

# TODO
vision.md -> post to okfn labs blog
vision-appendix.md -> post to okfn labs blog
```

## Tasks

* [x] create new directory `data-packages` and create the following pages: `csv.md, tabular.md`.
* [x] add `publish.md, publish-any.md, publish-faq.md, publish-geo.md, publish-online.md, publish-tabular.md` into `data-packages` directory and update links appropriately 
* [x] create `data-packages.md `

**Comment by Mikanebu** [comment]
FIXED

**Comment by rufuspollock** [comment]
And left-over vision docs migration is https://github.com/datahq/docs/issues/67
