### ISSUE TITLE
[showcase] Provide link to datapackage.json and add /datapackage.json "API"

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#81]
We want to have a link to `datapackage.json` of a dataset on the showcase page. It would allow users to see what metadata is being used to render a current page.

## Acceptance criteria

* [x] I can see `datapackage.json` for any dataset by going to `/{owner}/{name}/datapackage.json`
* [x] There is a link on `showcase` page that redirects to `datapackage.json` of a dataset

## Tasks

* [x] implement a new route using analysis below
  * [x] tests
* [x] analyse where we can put the link to `datapackage.json` on showcase page
  * [x] implement

## Analysis

`datapackage.json` is in `http://pkgstore.datahub.io/{owner}/{name}/latest/datapackage.json`

So we need to create `/{owner}/{name}/datapackage.json` route (see implementation for resources routes). Note that it will be "extended" `datapackage.json`.

```javascript
// in routes
router.get('/:owner/:name/datapackage.json', async (req, res) => {
  const userAndPkgId = await api.resolve(path.join(req.params.owner, req.params.name))
  // handle case when user doesnt exist here

  try {
    normalizedDp = await api.getPackage(userAndPkgId.userid, userAndPkgId.packageid)
  } catch (err) {
    if (err.name === 'BadStatusCode' && err.res.status === 404) {
      res.status(404).send('Sorry, we cannot locate that dataset for you.')
      return
    }
    throw err
  }

  res.redirect(`${normalizedDp.path}/datapackage.json`)
})
```

**Comment by rufuspollock** [comment]
@anuveyatsu please do a quick analysis before starting work.

**Comment by anuveyatsu** [comment]
@rufuspollock please see updated description of this issue ^^

**Comment by anuveyatsu** [comment]
FIXED, "API" for `datapackage.json` is implemented and we have a button in the bottom of showcase page:

<img width="828" alt="screen shot 2017-08-31 at 17 50 55" src="https://user-images.githubusercontent.com/17809581/29921822-f6fe86b0-8e74-11e7-96c5-d54c1e39380d.png">
