### ISSUE TITLE
[docs] Create proper docs home page

### ISSUE THREAD

**Issue by rufuspollock** [datahq/frontend#82]
Currently empty.

Planned sections:

* Getting started
* Examples
* Features
* Data Packages

## Acceptance criteria

* [x] nice docs home page

## Tasks

* [x] create `docs_home.html`
* [x] in docs router render `docs_home.html` if index page
* [x] update tests

**Comment by anuveyatsu** [comment]
FIXED, we may want to have docs navbar to navigate within docs, but it will go into another issue.

<img width="1280" alt="screen shot 2017-08-31 at 17 49 30" src="https://user-images.githubusercontent.com/17809581/29921776-c179d0da-8e74-11e7-84c8-1bf6250bc7c3.png">

**Comment by rufuspollock** [comment]
@anuveyatsu this looks fantastic - well done.

One small thing: Why is there no major page heading e.g. "Documentation" (instead we just have getting started).

Also how have you applied css (e.g. for the headings) just to this page (and not to all subdocs pages) (or do you intend to apply to all)?

**Comment by anuveyatsu** [comment]
@rufuspollock fixed. Now we have the major page heading "Documentation". Also applied css (text-center) for all `h1, h2 and p.description` tags within `body.docs`.
