### ISSUE TITLE
[docs] pushing single CSV file

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#84]
We want to have documentation about pushing data to datahub. There is already existing document in the getting started section - http://datahub.io/docs/getting-started/pushing-data

## Acceptance criteria

* [x] Nice and clear article about how to push data (single CSV file)

## Tasks

* [x] Plan
* [x] Write out the content
* [x] Put it online under `/docs/getting-started/pushing-data`

**Comment by anuveyatsu** [comment]
FIXED. See http://datahub.io/docs/getting-started/pushing-data
