### ISSUE TITLE
Track and show space usage in dashboard

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#88]
Implement changes from https://github.com/datahq/metastore/issues/14

*As a Publisher I want to know the total space I’m using (and perhaps breakdown by dataset) so that I know what this will cost.*

*As a Publisher I want to know the total number of my datasets.*

## Acceptance criteria

* [x] in my dashboard page, I can see total number of my packages and my total space usage

## Tasks

* [x] use search API in `/dashboard` route
  * [x] pass total number of packages to the view
  * [x] pass total space usage to the view
* [x] implement the template `dashboard.html` to use that data
* [x] refactor search and publisher pages to work with new search API

## Analysis

In `/routes/index.js`:

```javascript
...

router.get('/dashboard', async (req, res) => {
  if (req.cookies.jwt) {
    const isAuthenticated = await api.authenticate(req.cookies.jwt)
    if (isAuthenticated) {
      const packages = await api.search(`datahub.ownerid="${req.cookies.id}"&size=1`, req.cookies.jwt)
      const currentUser = utils.getCurrentUser(req.cookies)
      res.render('dashboard.html', {
        title: 'Dashboard',
        currentUser,
        totalPackages: packages.summary.total,
        totalSpace: bytes(packages.summary.totalBytes, {decimalPlaces: 0})
      })
    } else {
      req.flash('message', 'Your token has expired. Please, login to see your dashboard.')
      res.redirect('/')
    }
  } else {
    res.status(404).send('Sorry, this page was not found.')
    return
  }
})

...
```

and in `dashboard.html`:

```html
<table class="table table-dashboard">
  <thead>
    <tr>
      <th>PLAN</th>
      <th>PACKAGES</th>
      <th>ON DISK</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td class="main-info">Basic</td>
      <td class="main-info">{{ totalPackages }}</td>
      <td class="main-info">{{ totalSpace }}</td>
    </tr>
  </tbody>
</table>
```

**Comment by anuveyatsu** [comment]
FIXED

![dashboard-space-usage](https://user-images.githubusercontent.com/17809581/30208141-f5acc610-94b3-11e7-8597-f8a63e1cef6a.png)
