### ISSUE TITLE
Rework download files table in showcase page

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#90]
Have a mockup of files table - how it would look like (e.g., have xlsx, csv and pdf resources) in the showcase page.

## Acceptance criteria

* [x] the files table in the showcase page looks great (and its properties are approved by the team)
  * [x] Excel resources are rendered as per table in the analysis below

## Tasks

* [x] create a mockup of the table and discuss with rufus and adam
* [x] decide with final version of the table
* [x] implement in the frontend
* [x] work on dataset summary table. Is the size correct now? Revisit "created" and "updated" columns. Also, "source" column seems broken.
* [x] may be a bug or not but clicking on json link on https://datahub.io/core/s-and-p-500 gives me https://pkgstore.datahub.io/core/s-and-p-500:data_csv_preview/data/data_csv_preview.json - but surely the json link to should link to full json not the preview?

### Mockup of "data files" table in the showcase page

This is merged version of my proposal + Rufus and Adam's suggestion 

#### Excel with 2 sheets

|File|Description|Size|Last changed|Download|Other formats|
|----|-----------|----|------------|--------|-------------|
|myexcel|This is a sample excel file.|67kB|4d ago|myexcel [xlsx]||
|--myexcel-sheet-1|This is a sample csv file.|45kB|4d ago|myexcel-sheet-1 [csv]|myexcel-sheet-1 [json]|
|--myexcel-sheet-2|This is a sample csv file.|20kB|4d ago|myexcel-sheet-2 [csv]|myexcel-sheet-2 [json]|

So Excel with one sheet would contain first two rows of the table above...

#### Regular CSV and non-tabular resources

|File|Description|Size|Last changed|Download|Other formats|
|----|-----------|----|------------|--------|-------------|
|mycsv|My sample csv|10kB|5h ago|mycsv[csv]|mycsv[json]|mycsv[csv]
|mygeojson|My sample geojson|200kB|1m ago|mygeojson[geojson]||

#### How to implement

Instead of having lots of logic in the templates, we want to create a new function that would take either "extended" or "logical" datapackage.json and convert it into "good" one. By "good" datapackage.json we mean some object that is easy to iterate and render in the template, e.g., we just do for loop without any if statements and render whatever the object has:

```javascript
{
  ...
  resources: [...],
  downloads: [
    {
      name: <name>,
      format: <format>,
      description: <desc>,
      modified: <date>,
      size: <size>,
      download: <path>,
      otherFormats: [
        {
          name: <name>,
          format: <format>,
          size: <size>,
          download: <path>
        }
      ]
    },
    ...
  ]
}
```

```javascript
function logicalToGood(logical) {
  logical.resources.forEach(res => {
    if (res.format === 'xlsx' || res.format === 'xlsx') {
      // logic for excel file...
    } else {
      
    }
  })
}
```

---

### OLD analysis

As you can see we for non-csv files we won't have transformed versions:

| File    | Description                  | Size | Last changed | Original      | Transformed                |
|---------|------------------------------|------|--------------|----------------|----------------------------|
| mycsv   | This is a sample csv file.   | 45kB | 4d ago       | mycsv [csv]    | mycsv [csv] - mycsv [json] |
| myexcel | This is a sample excel file. | 67kB | 4d ago       | myexcel [xlsx] | (nothing here)             |
| mypdf   | This is a sample pdf file.   | 10kB | 4d ago       | mypdf [pdf]    | (nothing here)             |

> Quick qus:
> - why does myexcel not have transformed versions
> - for csv and excel i wonder if primary download is the CSV not Excel (but original is available)
>   - this is a bit tricky! Worth a chat with Adam
>   
> [name=Rufus Pollock]

> Yes, for mycsv and myexcel I would have the transformed csv as the primary download.
> So I would have 3 columns:
>   - Download
>   - Other formats
>   - Original (for reference, when applicable)
>   
> Resource | Download | Other Formats  | Original 
> --------|-----|--------------|----------
> mycsv   | CSV | JSON, SQLITE | Orig CSV
> myexcel | CSV | JSON, SQLITE | Orig XLS
> mypdf   | PDF | - | -
>
> [name=Adam Kariv]

Current look of the same table:

![](https://i.imgur.com/w9iX4Di.png)

**Comment by anuveyatsu** [comment]
FIXED, 
<img width="1025" alt="screen shot 2017-10-05 at 22 08 05" src="https://user-images.githubusercontent.com/17809581/31237779-b4ed1bc2-aa19-11e7-8f5a-7c516d6778fb.png">
