### ISSUE TITLE
[showcase] Per view urls

### ISSUE THREAD

**Issue by rufuspollock** [datahq/frontend#92]
As a datahub user I want to have URLs for each view so that I can embed the view in my own website; download the view in an automated way; direct link to the view (maybe better to do this in showcase)

* interactive embedding (e.g. in another site): html+js
* embed/include in a presentation: png (or svg)

As a datahub user I want to extract (download) views in html/png/svg so I can use it for different purposes. E.g., png is good for downloading and then using in documents/presentations.

```
# without any options it is just a showcase page showing the view (exact details tbc)
# html option would be for raw iframe embedding
/{owner}/{dataset}/v/{view-name-or-index}[.png|.svg]
/{owner}/{dataset}/v/{view-name-or-index}?embed=true
```

/{owner}/{dataset}/v/{view-name-or-index}

EMBED this view

## Acceptance criteria

* [ ] These are working:
  * [x] I get html for `/{owner}/{dataset}/v/{name/index}`
  * [ ] I get png for `/{owner}/{dataset}/v/{name/index}.png`
  * [ ] I get embed html for `/{owner}/{dataset}/v/{name/index}.html`
  * [ ] I get svg for `/{owner}/{dataset}/v/{name/index}.svg`

## Tasks

* [x] Analysis
* [x] implement url per view with no options
* [x] implement url per view for html embedding
* [ ] implement url per view for png
* [ ] implement url per view for svg

### URL for HTML

We can use bundle.js here - need to have div element with appropriate class name/id and pass datapackage.json with the correct view and only resources that are required for the view.

1. Filter out views using name/index
2. Identify which resource(s) needed for the view and filter out unnecessary resources
3. Render `view.html` template and pass filtered `datapackage.json`

`view.html` must not have header/footer etc - just do not include base/html:
```htmlmixed=
<!-- views -->
<div class="react-me part" data-type="data-views" id="next-section"></div>

<script type="text/javascript">
  var DP_ID = JSON.parse('{{ datapackageJson | safe }}');
</script>

<link rel="stylesheet" media="screen" href="/static/dpr-js/dist/main.css">
<script type="text/javascript" src="/static/dpr-js/dist/bundle.js"></script>
```

### URL for embedding HTML (iframe)

As a datahub user I want to have URLs for each view so that I can embed the view in my own website.

Path: `/{owner}/{name}/{index/name}.html`

We need to have a ready `iframe` element so users can just copy and paste it in their websites, e.g.:

`<iframe src="{pathToView}"></iframe>`

We can have it in the input element so it is obvious and easy to copy. `pathToView` here should be `/{owner}/{name}/{index/name}` without extension which is actual HTML for the view.

Underneath, we can have an example of how it would look like - it is basically actual embedding into to the current page.

### URL for svg

Both Plotly and Vega libs render `svg` in showcase page. E.g., see https://datahub.io/core/finance-vix and http://datahub.io/examples/vega-views-tutorial-lines

We need to take `svg` element from the DOM and render it separately for `/{owner}/{name}/{index/name}.svg`:

* Plotly contains 2 `svg` elements - first one for graph itself and second one is for additional layers such as info, hover, zoom etc. So we need only the first element (`class="main-svg"`)
* Vega contains only one `svg` with `class="marks"`

### URL for png

Refer to URL for svg. Once we have svg we can easily convert it to png:

* https://github.com/domenic/svg2png

However, we probably want to do svg2png conversion in browser. In this case: https://gist.github.com/mbostock/6466603#2-convert-svg-to-png

**Comment by anuveyatsu** [comment]
FIXED basic per view URLs, e.g., see https://datahub.io/core/finance-vix/view/0 - you should provide either view name or index without extension. You also can see how to share or embed a view in the showcase page under the graph - https://datahub.io/core/finance-vix

We will open new issues in the future for other parts of this issue, eg, `png` version of the view.
