### ISSUE TITLE
Misc items for 25 Sep 2017

### ISSUE THREAD

**Issue by anuveyatsu** [datahq/frontend#96]
## Tasks

* Theme
  * [x] [30m] Footer does not stick at the bottom of the page if the content is small.
* Showcase page
  * [x] [20m] handle INVALID state of pipelines - do the same logic as for FAILED
  * [x] [20m] paths in resources are now URLs (and not relative)
  * [ ] [15m] have file size/rowcount next to each preview table's title
* Front page
  * [ ] [20m] LOW (do as part of other work) Reuse snippet to list datasets - atm, it is different from search/publisher pages list.
* Dashboard page
  * [ ] [30m] LOW in the dashboard replace email with username (we can still have email somewhere underneath in smaller font)
  * [x] [1m] in the dashboard rename “packages” => “datasets"
* Docs
  * [ ] [1h] LOW the info box in http://datahub.io/docs/getting-started/pushing-data looks a bit poor (and distracting ...). If we going to have the info box can we style it nicely e.g. put an info sign inside of it and/or colour it etc.
  * [ ] [20m] LOW spacing after images is weird http://datahub.io/docs/getting-started/pushing-data (e.g. around the "It’s may still be processing and in that case you would see the following:")
* Analytics
  * [x] [30m] track downloads of derived resource versions in GA

**Comment by anuveyatsu** [comment]
FIXED mostly. Remaining work will be done as a part of major improvements later.
